import { createFileRoute } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Link } from "@/lib/router-compat";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";
import Navbar from "@/components/Navbar";
import { Check, Flame, ArrowRight, Sparkles, Target, Globe2 } from "lucide-react";
import { toast } from "sonner";

export const Route = createFileRoute("/for-you")({ ssr: false, component: ForYouPage });

function ForYouPage() {
  const { user, loading } = useAuth();
  const qc = useQueryClient();
  const [goalTitle, setGoalTitle] = useState("");
  const [savingGoal, setSavingGoal] = useState(false);
  const { data: profile } = useQuery({ queryKey:["growth-profile",user?.id], enabled:!!user, queryFn:async()=>{const {data,error}=await supabase.from("profiles").select("full_name,target_career,interests,country_code,education_level,university,program").eq("id",user!.id).maybeSingle(); if(error) throw error; return data;}});
  const { data: goals=[] } = useQuery({ queryKey:["path-goals",user?.id], enabled:!!user, queryFn:async()=>{const {data,error}=await supabase.from("path_goals").select("*").eq("user_id",user!.id).eq("status","active").order("created_at",{ascending:false}); if(error) throw error; return data??[];}});
  const { data: actions=[] } = useQuery({ queryKey:["path-actions",user?.id], enabled:!!user, queryFn:async()=>{const {data,error}=await supabase.from("path_actions").select("*").eq("user_id",user!.id).is("completed_at",null).order("priority").order("position").limit(8); if(error) throw error; return data??[];}});
  const { data: streak } = useQuery({ queryKey:["path-streak",user?.id], enabled:!!user, queryFn:async()=>{const {data,error}=await supabase.from("path_streaks").select("*").eq("user_id",user!.id).maybeSingle(); if(error) throw error; return data;}});
  const { data: opportunities=[] } = useQuery({ queryKey:["for-you-opportunities",profile?.target_career,profile?.country_code], enabled:!loading, queryFn:async()=>{let q=supabase.from("opportunities").select("id,title,opportunity_type,company_name,country,location,remote,deadline,deadline_date,skills,skills_required,source_url,apply_url,verified").eq("is_active",true).order("deadline",{ascending:true,nullsFirst:false}).limit(8); if(profile?.country_code) q=q.or(`country_code.eq.${profile.country_code},country.eq.${profile.country_code}`); const {data,error}=await q; if(error) throw error; return data??[];}});
  const { data: countries=[] } = useQuery({ queryKey:["international-countries"], queryFn:async()=>{const {data,error}=await supabase.from("international_country_directory").select("country_code,country_name,region,verification_status,last_verified_at").order("country_name").limit(12); if(error) throw error; return data??[];}});
  const firstName=profile?.full_name?.split(" ")[0]||"there";
  const nextAction=actions[0]; const goal=goals[0];
  const readiness=useMemo(()=>{let score=20; if(profile?.target_career)score+=25; if(profile?.interests?.length)score+=15; if(profile?.education_level||profile?.university)score+=15; if(goals.length)score+=15; if(streak?.total_actions)score+=10; return Math.min(score,100);},[profile,goals.length,streak?.total_actions]);
  const createGoal=async()=>{if(!user||!goalTitle.trim())return; setSavingGoal(true); const {data,error}=await supabase.from("path_goals").insert({user_id:user.id,title:goalTitle.trim(),target_type:"career"}).select().single(); if(!error&&data){await supabase.from("path_actions").insert([{user_id:user.id,goal_id:data.id,title:`Define the first milestone for ${goalTitle.trim()}`,description:"Turn the goal into one concrete action you can complete this week.",action_type:"next_step",priority:1,position:0},{user_id:user.id,goal_id:data.id,title:"Find one relevant opportunity",description:"Save one scholarship, internship, programme or job connected to this goal.",action_type:"opportunity",priority:2,position:1}]); setGoalTitle(""); await qc.invalidateQueries({queryKey:["path-goals"]}); await qc.invalidateQueries({queryKey:["path-actions"]}); toast.success("Your path has been created.");} else toast.error(error?.message||"Could not create your path."); setSavingGoal(false);};
  const completeAction=async(id:string)=>{if(!user)return; const today=new Date().toISOString().slice(0,10), yesterday=new Date(Date.now()-86400000).toISOString().slice(0,10); const {error}=await supabase.from("path_actions").update({completed_at:new Date().toISOString()}).eq("id",id).eq("user_id",user.id); if(error){toast.error(error.message);return;} const current=streak?.last_action_date; const currentStreak=current===today?(streak?.current_streak??0):current===yesterday?(streak?.current_streak??0)+1:1; await supabase.from("path_streaks").upsert({user_id:user.id,current_streak:currentStreak,longest_streak:Math.max(currentStreak,streak?.longest_streak??0),last_action_date:today,total_actions:(streak?.total_actions??0)+1}); await qc.invalidateQueries({queryKey:["path-actions"]}); await qc.invalidateQueries({queryKey:["path-streak"]}); toast.success("Progress saved.");};
  return <div className="min-h-screen bg-background pt-20 pb-24"><Navbar/><main className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 space-y-6">
    <section className="rounded-2xl border border-border bg-card p-5 sm:p-7"><div className="flex flex-col lg:flex-row lg:items-end lg:justify-between gap-5"><div><p className="text-xs uppercase tracking-[0.18em] text-primary font-semibold">For You</p><h1 className="mt-2 text-3xl sm:text-4xl font-bold">Good to see you, {firstName}.</h1><p className="mt-2 max-w-2xl text-muted-foreground">Your goals, next actions, opportunities and global pathways in one place.</p></div><Link to="/career-simulator" className="inline-flex items-center justify-center gap-2 rounded-xl bg-primary px-4 py-3 text-sm font-semibold text-primary-foreground">Simulate a career <ArrowRight className="h-4 w-4"/></Link></div></section>
    <section className="grid gap-4 md:grid-cols-3"><div className="rounded-2xl border border-border bg-card p-5"><div className="flex items-center justify-between"><span className="text-sm text-muted-foreground">Path readiness</span><Target className="h-4 w-4 text-primary"/></div><div className="mt-3 text-4xl font-bold">{readiness}%</div><div className="mt-3 h-2 rounded-full bg-secondary"><div className="h-2 rounded-full bg-primary" style={{width:`${readiness}%`}}/></div></div><div className="rounded-2xl border border-border bg-card p-5"><div className="flex items-center gap-2 text-sm text-muted-foreground"><Flame className="h-4 w-4 text-primary"/> Path streak</div><div className="mt-3 text-4xl font-bold">{streak?.current_streak??0}</div><p className="mt-1 text-xs text-muted-foreground">Longest: {streak?.longest_streak??0} · Total actions: {streak?.total_actions??0}</p></div><div className="rounded-2xl border border-border bg-card p-5"><div className="flex items-center gap-2 text-sm text-muted-foreground"><Sparkles className="h-4 w-4 text-primary"/> Main goal</div><div className="mt-3 text-lg font-semibold">{goal?.title||profile?.target_career||"Set your first goal"}</div><p className="mt-1 text-xs text-muted-foreground">{goal?`${goal.progress}% complete`:"A goal unlocks a personalized action loop."}</p></div></section>
    <section className="grid gap-5 lg:grid-cols-[1.25fr_.75fr]"><div className="rounded-2xl border border-border bg-card p-5"><div className="flex items-center justify-between gap-3"><h2 className="text-lg font-semibold">Your next actions</h2><span className="text-xs text-muted-foreground">Small actions, measurable progress</span></div><div className="mt-4 space-y-3">{actions.length?actions.map((a:any)=><div key={a.id} className="flex items-start gap-3 rounded-xl border border-border/70 p-4"><button onClick={()=>void completeAction(a.id)} className="mt-0.5 grid h-7 w-7 place-items-center rounded-full border border-border hover:border-primary hover:text-primary" aria-label={`Complete ${a.title}`}><Check className="h-4 w-4"/></button><div className="min-w-0"><p className="font-medium">{a.title}</p><p className="mt-1 text-sm text-muted-foreground">{a.description}</p></div></div>):<p className="text-sm text-muted-foreground">No open actions. Create a goal to generate your first path.</p>}</div><div className="mt-5 flex flex-col sm:flex-row gap-2"><input value={goalTitle} onChange={e=>setGoalTitle(e.target.value)} placeholder="e.g. Become a machine learning engineer" className="min-h-11 flex-1 rounded-xl border border-border bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-primary/40"/><button disabled={savingGoal||!goalTitle.trim()} onClick={()=>void createGoal()} className="min-h-11 rounded-xl bg-primary px-4 text-sm font-semibold text-primary-foreground disabled:opacity-50">{savingGoal?"Creating...":"Create path"}</button></div></div>
    <div className="rounded-2xl border border-border bg-card p-5"><h2 className="text-lg font-semibold">Opportunity radar</h2><p className="mt-1 text-sm text-muted-foreground">Fresh opportunities connected to your profile.</p><div className="mt-4 space-y-3">{opportunities.slice(0,5).map((o:any)=><a key={o.id} href={o.apply_url||o.source_url||"#"} target="_blank" rel="noreferrer" className="block rounded-xl border border-border/70 p-3 hover:border-primary/50"><p className="text-sm font-medium">{o.title}</p><p className="mt-1 text-xs text-muted-foreground">{o.company_name||o.organisation||o.country||"Global"}{o.remote?" · Remote":""}</p></a>)}{!opportunities.length&&<p className="text-sm text-muted-foreground">No matching opportunities are available right now.</p>}</div><Link to="/career-marketplace" className="mt-4 inline-flex items-center gap-1 text-sm font-medium text-primary">Explore all <ArrowRight className="h-4 w-4"/></Link></div></section>
    <section className="rounded-2xl border border-border bg-card p-5"><div className="flex items-center gap-2"><Globe2 className="h-5 w-5 text-primary"/><h2 className="text-lg font-semibold">Global pathways</h2></div><p className="mt-1 text-sm text-muted-foreground">Explore country application pathways from your workspace.</p><div className="mt-4 grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6 gap-2">{countries.map((c:any)=><Link key={c.country_code} to={`/international-directory?country=${encodeURIComponent(c.country_code)}`} className="rounded-xl border border-border/70 p-3 hover:border-primary/50"><p className="text-sm font-medium">{c.country_name}</p><p className="text-xs text-muted-foreground mt-1">{c.region}</p></Link>)}</div><Link to="/international-directory" className="mt-4 inline-flex items-center gap-1 text-sm font-medium text-primary">Open international directory <ArrowRight className="h-4 w-4"/></Link></section>
    {!user&&<div className="rounded-2xl border border-primary/30 bg-primary/5 p-5 text-sm text-muted-foreground">Sign in to save goals, actions and streak progress.</div>}
  </main></div>;
}
export default ForYouPage;