import { createFileRoute } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { supabase } from "@/integrations/supabase/client";
type Student = { id:string; country_code:string|null; university_name:string|null; programme_name:string|null; academic_level:string|null; graduation_year:number|null; skills:string[]|null; interests:string[]|null; linkedin_url:string|null; github_url:string|null; portfolio_url:string|null; open_to_collaboration:boolean|null; open_to_mentorship:boolean|null; looking_for_opportunities:boolean|null };
export const Route = createFileRoute("/international-students")({ component: InternationalStudents });
function InternationalStudents(){
 const [search,setSearch]=useState("");
 const q=useQuery({queryKey:["international-students"],queryFn:async()=>{const {data,error}=await supabase.from("international_students").select("id,country_code,university_name,programme_name,academic_level,graduation_year,skills,interests,linkedin_url,github_url,portfolio_url,open_to_collaboration,open_to_mentorship,looking_for_opportunities").eq("visible",true).order("created_at",{ascending:false});if(error)throw error;return (data??[]) as Student[];}});
 const rows=useMemo(()=> (q.data??[]).filter(x=>[x.country_code,x.university_name,x.programme_name,...(x.skills??[]),...(x.interests??[])].filter(Boolean).join(" ").toLowerCase().includes(search.toLowerCase())),[q.data,search]);
 return <div className="min-h-dvh bg-background"><Navbar/><main className="pt-20 pb-14 px-4 sm:px-8"><div className="max-w-7xl mx-auto"><p className="text-xs uppercase tracking-[.18em] text-primary font-semibold">Community</p><h1 className="text-3xl sm:text-4xl font-bold mt-2">International Student Directory</h1><p className="mt-2 text-muted-foreground max-w-2xl">Discover students and young professionals across countries, universities and fields. Profiles appear only when the owner has opted in to public visibility.</p><input className="mt-6 h-11 w-full rounded-lg border border-border bg-background px-3" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search country, university, programme or skill" aria-label="Search international students"/>
 {q.isLoading?<div className="mt-8 grid sm:grid-cols-2 lg:grid-cols-3 gap-4">{Array.from({length:6}).map((_,i)=><div key={i} className="h-44 rounded-xl bg-secondary animate-pulse"/>)}</div>:<div className="mt-8 grid sm:grid-cols-2 lg:grid-cols-3 gap-4">{rows.map(x=><article key={x.id} className="rounded-xl border border-border bg-card p-5"><p className="text-xs text-primary font-semibold">{x.country_code??"International"}</p><h2 className="font-semibold mt-1">{x.university_name??"University not listed"}</h2><p className="text-sm text-muted-foreground">{x.programme_name??"Programme not listed"}{x.academic_level ? " · "+x.academic_level : ""}</p>{x.graduation_year&&<p className="text-xs text-muted-foreground mt-2">Graduation: {x.graduation_year}</p>}<div className="flex flex-wrap gap-1 mt-3">{(x.skills??[]).slice(0,5).map(s=><span key={s} className="text-xs px-2 py-1 rounded-full bg-secondary">{s}</span>)}</div><div className="flex gap-3 mt-4 text-xs">{x.open_to_collaboration&&<span>Collaboration</span>}{x.open_to_mentorship&&<span>Mentorship</span>}{x.looking_for_opportunities&&<span>Opportunities</span>}</div><div className="flex gap-3 mt-4">{x.linkedin_url&&<a className="text-xs text-primary hover:underline" href={x.linkedin_url} target="_blank" rel="noreferrer">LinkedIn</a>}{x.github_url&&<a className="text-xs text-primary hover:underline" href={x.github_url} target="_blank" rel="noreferrer">GitHub</a>}{x.portfolio_url&&<a className="text-xs text-primary hover:underline" href={x.portfolio_url} target="_blank" rel="noreferrer">Portfolio</a>}</div></article>)}</div>}
 {!q.isLoading&&!rows.length&&<div className="mt-8 p-8 text-center border border-dashed border-border rounded-xl text-muted-foreground">No opted-in international profiles match your search.</div>}</div></main><Footer/></div>;
}