import { useQuery } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
const card="rounded-xl border border-border bg-card p-5";
const Layout=({title,kicker,children}:{title:string;kicker:string;children:React.ReactNode})=><div className="min-h-dvh bg-background text-foreground"><Navbar/><main className="mx-auto max-w-7xl px-4 pb-24 pt-20 sm:px-6 lg:px-8"><p className="text-sm font-semibold text-primary">{kicker}</p><h1 className="mt-1 text-3xl font-bold">{title}</h1>{children}</main><Footer/></div>;

const newsCategories=["Tech","Startup","Business","Politics","Education","Health","Entertainment"];
const innovationCategories=["AI","Robotics","Semiconductors","Climate","HealthTech","FinTech","Mobility","Space","Deep Tech","African Startups"];

export function News(){
 const {data=[],isLoading}=useQuery({queryKey:["live-news"],queryFn:async()=>{const r=await fetch("/api/news-feed?type=news");if(!r.ok)throw new Error("news");return await r.json();}});
 return <Layout title="News" kicker="SOURCE-BACKED NEWS"><p className="mt-2 max-w-3xl text-muted-foreground">Live source-linked coverage. Each category requests up to 20 current stories and shows the source and publication date.</p><div className="mt-6 flex gap-2 overflow-x-auto">{newsCategories.map(c=><span key={c} className="rounded-full border border-border px-3 py-2 text-sm">{c}</span>)}</div>{isLoading?<p className="mt-8 text-muted-foreground">Loading current sources...</p>:<div className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{(data.items||[]).map((n:any,i:number)=><article key={n.url||i} className={card}><p className="text-xs font-semibold uppercase text-primary">{n.category}</p><h2 className="mt-2 font-semibold">{n.title}</h2><p className="mt-2 text-sm text-muted-foreground">{n.source} · {n.publishedAt?new Date(n.publishedAt).toLocaleDateString():"Date unavailable"}</p><a href={n.url} target="_blank" rel="noreferrer" className="mt-4 inline-block text-sm font-semibold text-primary">Read source →</a></article>)}</div>}</Layout>;
}

export function Innovation(){
 const {data=[],isLoading}=useQuery({queryKey:["innovation-live"],queryFn:async()=>{const r=await fetch("/api/news-feed?type=innovation");if(!r.ok)throw new Error("innovation");return await r.json();}});
 return <Layout title="Innovation" kicker="INNOVATION INTELLIGENCE"><p className="mt-2 max-w-3xl text-muted-foreground">Current source-linked developments across AI, robotics, semiconductors, climate, health, finance, mobility, space and African startups.</p><div className="mt-6 flex gap-2 overflow-x-auto">{innovationCategories.map(c=><span key={c} className="rounded-full border border-border px-3 py-2 text-sm">{c}</span>)}</div>{isLoading?<p className="mt-8 text-muted-foreground">Loading innovation sources...</p>:<div className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{(data.items||[]).map((n:any,i:number)=><article key={n.url||i} className={card}><p className="text-xs font-semibold uppercase text-primary">{n.category}</p><h2 className="mt-2 font-semibold">{n.title}</h2><p className="mt-2 text-sm text-muted-foreground">{n.source} · {n.publishedAt?new Date(n.publishedAt).toLocaleDateString():"Date unavailable"}</p><a href={n.url} target="_blank" rel="noreferrer" className="mt-4 inline-block text-sm font-semibold text-primary">Read source →</a></article>)}</div>}</Layout>;
}

export function Feed(){
 const categories=["AI","Robotics","Innovation","Education","Startup","Science","Culture","Ghana"];
 const {data=[],isLoading}=useQuery({queryKey:["feed-items"],queryFn:async()=>{const {data,error}=await supabase.from("feed_items").select("*").order("published_at",{ascending:false}).limit(500);if(error)throw error;return data??[];}});
 return <Layout title="Feed" kicker="MEDIA FEED"><p className="mt-2 max-w-3xl text-muted-foreground">Public media from verified sources. Video cards show an inline player when the source is embeddable and always retain the original URL.</p><div className="mt-6 flex gap-2 overflow-x-auto">{categories.map(c=><span key={c} className="rounded-full border border-border px-3 py-2 text-sm">{c}</span>)}</div><div className="mt-8 grid gap-5 lg:grid-cols-2">{data.map((p:any)=><article key={p.id} className={card+" overflow-hidden p-0"}>{p.video_url?<div className="aspect-video bg-muted"><iframe className="h-full w-full" src={p.video_url.includes("youtube.com/watch?v=")?p.video_url.replace("watch?v=","embed/"):(p.video_url.includes("youtu.be/")?p.video_url.replace("youtu.be/","youtube.com/embed/"):p.video_url)} title={p.title} loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen/></div>:null}<div className="p-5"><p className="text-xs font-semibold uppercase text-primary">{p.category}</p><h2 className="mt-2 font-semibold">{p.title}</h2><p className="mt-2 text-sm text-muted-foreground">{p.description||""}</p><p className="mt-3 text-xs text-muted-foreground">{p.source_name} · {p.published_at?new Date(p.published_at).toLocaleDateString():""}</p><a href={p.source_url} target="_blank" rel="noreferrer" className="mt-2 block break-all text-xs text-primary underline">{p.source_url}</a></div></article>)}</div>{!isLoading&&!data.length&&<div className={card+" mt-8"}>No verified feed items have been ingested yet. The platform will not fabricate videos to reach a count.</div>}</Layout>;
}
