import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Link } from "@/lib/router-compat";
import Navbar from "@/components/Navbar";
import MobileTabBar from "@/components/MobileTabBar";
import Footer from "@/components/Footer";
import { supabase } from "@/integrations/supabase/client";
import { EMPLOYERS } from "@/data/employers";
const sb:any=supabase;
const shell="min-h-dvh bg-background text-foreground";
const card="rounded-xl border border-border bg-card p-5";
function Layout({title,children}:{title:string;children:React.ReactNode}){return <div className={shell}><Navbar/><main className="mx-auto max-w-7xl px-4 pb-24 pt-20 sm:px-6 lg:px-8"><p className="text-sm font-semibold text-primary">DIRECTORY</p><h1 className="mt-1 text-3xl font-bold">{title}</h1>{children}</main><MobileTabBar/><Footer/></div>}

export function StudentDirectory(){const [q,setQ]=useState("");const {data=[],isLoading,error}=useQuery({queryKey:["student-directory"],queryFn:async()=>{const {data,error}=await sb.from("universities").select("id,name,short_name,location,region,slug,verified").order("name").limit(500);if(error)throw error;return data??[];}});const rows=data.filter((x:any)=>(String(x.name??"")+" "+String(x.short_name??"")).toLowerCase().includes(q.toLowerCase()));return <Layout title="Student Directory"><p className="mt-2 text-muted-foreground">Browse institutions and continue into each university profile.</p><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search universities" className="mt-6 w-full max-w-xl rounded-lg border border-border bg-background px-3 py-2.5"/>{isLoading?<p className="mt-8 text-muted-foreground">Loading universities...</p>:error?<div className={card+" mt-6"}>The student directory could not load.</div>:<div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{rows.map((u:any)=><Link key={u.id} to={"/university/"+u.slug} className={card+" hover:border-primary"}><h2 className="font-semibold">{u.short_name||u.name}</h2><p className="mt-1 text-sm text-muted-foreground">{u.location||u.region||"Ghana"}</p><span className="mt-4 inline-block text-sm font-semibold text-primary">Open university →</span></Link>)}</div>}</Layout>}

export function EmployeeDirectory(){const {data=[],isLoading}=useQuery({queryKey:["employee-directory"],queryFn:async()=>{const {data,error}=await sb.from("talent_directory").select("user_id,full_name,professional_title,years_experience,linkedin_url,city,preferred_industries,skills,bio").eq("discoverable",true).order("full_name").limit(200);if(error)throw error;return data??[];}});return <Layout title="Employee Directory"><p className="mt-2 text-muted-foreground">Professionals who explicitly opted into recruiter discovery.</p>{isLoading?<p className="mt-8 text-muted-foreground">Loading talent...</p>:<div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{data.map((x:any)=><article key={x.user_id} className={card}><h2 className="font-semibold">{x.full_name||"Professional"}</h2><p className="mt-1 text-sm text-muted-foreground">{x.professional_title||"Professional"}{x.city?" · "+x.city:""}</p><p className="mt-2 text-xs text-muted-foreground">{Number(x.years_experience||0)} years experience</p><p className="mt-3 text-xs text-muted-foreground">{(x.skills||[]).slice(0,5).join(" · ")}</p>{x.linkedin_url&&<a href={x.linkedin_url} target="_blank" rel="noreferrer" className="mt-4 inline-block text-sm font-semibold text-primary">Public LinkedIn →</a>}</article>)}</div>}</Layout>}

export function EmployerDirectory(){const [q,setQ]=useState("");const {data=[]}=useQuery({queryKey:["employer-directory"],queryFn:async()=>{const {data}=await sb.from("employers").select("id,name,organization_type,industry,country_code,city,website_url,description,verification_status").order("name").limit(200);return data??[];}});const dbRows=data as any[];const merged=[...dbRows,...EMPLOYERS.map(x=>({id:"catalog-"+x.id,name:x.name,industry:x.sector,city:x.locations[0],website_url:x.url,description:x.about}))];const seen=new Set<string>();const rows=merged.filter(x=>{const k=String(x.name).toLowerCase();if(seen.has(k))return false;seen.add(k);return k.includes(q.toLowerCase())});return <Layout title="Employer Directory"><p className="mt-2 text-muted-foreground">Employer profiles and official career sources.</p><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search employers" className="mt-6 w-full max-w-xl rounded-lg border border-border bg-background px-3 py-2.5"/><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{rows.slice(0,200).map((x:any)=><article key={x.id} className={card}><h2 className="font-semibold">{x.name}</h2><p className="mt-1 text-xs text-muted-foreground">{x.industry||"Employer"} · {x.city||"Africa"}</p><p className="mt-2 text-sm text-muted-foreground line-clamp-3">{x.description||"Employer profile and career information."}</p>{x.website_url&&<a href={x.website_url} target="_blank" rel="noreferrer" className="mt-4 inline-block text-sm font-semibold text-primary">Official careers / website →</a>}</article>)}</div></Layout>}

export function StartupDirectory(){const {data=[],isLoading}=useQuery({queryKey:["startup-directory"],queryFn:async()=>{const {data,error}=await sb.from("african_startups").select("*").order("capital_usd",{ascending:false}).limit(500);if(error)throw error;return data??[];}});return <Layout title="Startup Directory"><p className="mt-2 max-w-2xl text-muted-foreground">African startup intelligence based on publicly reported funding or valuation of at least US$1m. This is a public-data directory, not a completeness claim.</p>{isLoading?<p className="mt-8 text-muted-foreground">Loading startup intelligence...</p>:<div className="mt-6 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-border"><th className="py-3 pr-4">Company</th><th className="py-3 pr-4">Country</th><th className="py-3 pr-4">Sector</th><th className="py-3 pr-4">Stage</th><th className="py-3 pr-4">Reported capital</th><th className="py-3 pr-4">Source</th></tr></thead><tbody>{data.map((x:any)=><tr key={x.id} className="border-b border-border/60"><td className="py-3 pr-4 font-medium">{x.company_name}</td><td className="py-3 pr-4">{x.country||"Africa"}</td><td className="py-3 pr-4">{x.sector||"Technology"}</td><td className="py-3 pr-4">{x.stage||"—"}</td><td className="py-3 pr-4">{"$"+Number(x.capital_usd||0).toLocaleString()}</td><td className="py-3 pr-4"><a className="text-primary font-semibold" href={x.source_url} target="_blank" rel="noreferrer">Source →</a></td></tr>)}</tbody></table></div>}</Layout>}
