
import { useEffect, useMemo, useRef, useState } from "react";
import Navbar from "@/components/Navbar";
import Seo from "@/components/Seo";
import { Heart, MessageCircle, Volume2, VolumeX } from "@/lib/icons";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";

const categories=["For You","Tech","Education","Startup","Science","Culture","Ghana"];
type Post={id:string;title:string|null;description:string|null;video_url:string|null;youtube_url:string|null;thumbnail_url:string|null;tags:string[];category:string;likes_count:number;comments_count:number;views_count:number;is_published:boolean;created_at:string};

export default function Feed(){
  const {user}=useAuth();
  const [posts,setPosts]=useState<Post[]>([]);
  const [category,setCategory]=useState("For You");
  const [muted,setMuted]=useState(true);
  const refs=useRef<Record<string,HTMLVideoElement|null>>({});
  useEffect(function(){void supabase.from("feed_posts").select("id,title,description,video_url,youtube_url,thumbnail_url,tags,category,likes_count,comments_count,views_count,is_published,created_at").eq("is_published",true).order("created_at",{ascending:false}).limit(60).then(function(r){if(r.data)setPosts(r.data as Post[]);});},[]);
  const visible=useMemo(function(){if(category==="For You")return posts;return posts.filter(function(p){return p.category.toLowerCase()===category.toLowerCase() || p.tags.some(function(tag){return tag.toLowerCase()===category.toLowerCase();});});},[posts,category]);
  useEffect(function(){const observer=new IntersectionObserver(function(entries){entries.forEach(function(entry){const video=entry.target as HTMLVideoElement;if(entry.isIntersecting)void video.play().catch(function(){});else video.pause();});},{threshold:0.65});visible.forEach(function(p){const video=refs.current[p.id];if(video)observer.observe(video);});return function(){observer.disconnect();};},[visible]);
  async function like(postId:string){if(!user){window.location.href="/auth";return;}const r=await supabase.rpc("toggle_feed_like",{p_post_id:postId});if(r.error)return;setPosts(function(current){return current.map(function(p){return p.id===postId?{...p,likes_count:Math.max(0,p.likes_count+(r.data ? 1 : -1))}:p;});});}
  return <div className="min-h-dvh bg-background"><Navbar/><main className="mx-auto max-w-4xl px-0 pb-24 pt-14 sm:px-4"><Seo title="Feed | GhanaPathFinder" description="A vertical community feed for education, technology, startups, science and culture." path="/feed"/><div className="sticky top-14 z-30 border-y border-border bg-background/95 px-3 py-2 backdrop-blur"><div className="flex gap-2 overflow-x-auto">{categories.map(function(c){return <button key={c} type="button" onClick={function(){setCategory(c);}} className={"shrink-0 border px-3 py-1.5 text-xs " + (category===c ? "border-primary bg-primary text-primary-foreground" : "border-border")}>{c}</button>;})}</div></div><div className="mt-3 space-y-3">{visible.map(function(post){return <article key={post.id} className="relative min-h-[70dvh] overflow-hidden bg-black"><div className="absolute inset-0">{post.video_url ? <video ref={function(el){refs.current[post.id]=el;}} className="h-full w-full object-cover" src={post.video_url} poster={post.thumbnail_url||undefined} muted={muted} playsInline loop preload="metadata"/> : post.thumbnail_url ? <img src={post.thumbnail_url} alt="" className="h-full w-full object-cover"/> : <div className="h-full w-full"/>}</div><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/85 via-black/35 to-transparent p-5 pt-24 text-white"><p className="text-xs uppercase tracking-wide opacity-80">{post.category}</p><h2 className="mt-1 text-xl font-semibold">{post.title || "GhanaPathFinder community"}</h2><p className="mt-2 max-w-2xl text-sm text-white/80">{post.description||""}</p></div><div className="absolute bottom-5 right-4 flex flex-col gap-2"><button type="button" onClick={function(){void like(post.id);}} className="grid h-11 w-11 place-items-center rounded-full bg-white/15 text-white backdrop-blur" aria-label="Like"><Heart className="h-5 w-5"/></button><button type="button" onClick={function(){setMuted(function(value){return !value;});}} className="grid h-11 w-11 place-items-center rounded-full bg-white/15 text-white backdrop-blur" aria-label="Toggle sound">{muted?<VolumeX className="h-5 w-5"/>:<Volume2 className="h-5 w-5"/>}</button><button type="button" className="grid h-11 w-11 place-items-center rounded-full bg-white/15 text-white backdrop-blur" aria-label="Comments"><MessageCircle className="h-5 w-5"/></button></div></article>;})}{!visible.length&&<div className="border border-dashed border-border p-6 text-sm text-muted-foreground">No published feed videos are available yet.</div>}</div></main></div>
}
