import { useQuery } from "@tanstack/react-query";
import Navbar from "@/components/Navbar";
import { Link } from "@/lib/router-compat";
import { ExternalLink } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";

const Ghana=()=>{
 const uni=useQuery({queryKey:["ghana-universities"],queryFn:async()=>{const {data,error}=await supabase.from("universities").select("id,name,slug,city,region,verified,official_url").eq("country","Ghana").order("name").limit(40);if(error)throw error;return data??[];}});
 const opp=useQuery({queryKey:["ghana-opportunities"],queryFn:async()=>{const {data,error}=await supabase.from("opportunities").select("id,title,company_name,organisation,city,category,deadline_date,apply_url,source_url,verified,is_active,published").eq("country","Ghana").or("is_active.eq.true,published.eq.true").order("posted_at",{ascending:false}).limit(12);if(error)throw error;return data??[];}});
 return <div className="min-h-screen bg-background pt-20 pb-24"><Navbar/><main className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8"><header className="mb-8"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-primary">Country hub</p><h1 className="mt-2 text-3xl font-bold">Ghana</h1><p className="mt-2 max-w-2xl text-sm text-muted-foreground">GhanaPathFinder's deepest country catalogue, using records already verified or stored in the platform.</p></header><section className="mb-8"><div className="mb-3 flex items-center justify-between"><h2 className="text-xl font-semibold">Universities</h2><Link to="/programmes" className="text-xs font-semibold text-primary">Browse programmes</Link></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{uni.data?.map(x=><Link key={x.id} to="/university/$slug" params={{slug:x.slug}} className="rounded-xl border border-border bg-card p-4"><h3 className="font-semibold text-sm">{x.name}</h3><p className="mt-1 text-xs text-muted-foreground">{[x.city,x.region].filter(Boolean).join(" · ")}{x.verified?" · Verified":""}</p></Link>)}</div></section><section><h2 className="mb-3 text-xl font-semibold">Ghana opportunities</h2><div className="grid gap-3 md:grid-cols-2">{opp.data?.map(x=><article key={x.id} className="rounded-xl border border-border bg-card p-4"><h3 className="font-semibold">{x.title}</h3><p className="mt-1 text-xs text-muted-foreground">{x.company_name||x.organisation||"Organisation"}{x.city?" · "+x.city:""}{x.category?" · "+x.category:""}</p>{x.deadline_date&&<p className="mt-2 text-xs text-muted-foreground">Deadline: {new Date(x.deadline_date).toLocaleDateString()}</p>}{(x.apply_url||x.source_url)&&<a href={x.apply_url||x.source_url||"#"} target="_blank" rel="noreferrer" className="mt-3 inline-flex items-center gap-1 text-xs font-semibold text-primary">Open source <ExternalLink className="h-3.5 w-3.5"/></a>}</article>)}</div>{!opp.isLoading&&!opp.data?.length&&<div className="mt-4 rounded-xl border border-dashed border-border p-6 text-sm text-muted-foreground">No current Ghana opportunities match the catalogue filters.</div>}</section></main></div>;
};
export default Ghana;
