import { useQuery } from "@tanstack/react-query";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { supabase } from "@/integrations/supabase/client";

type Kind = "jobs"|"companies"|"startups"|"people"|"events"|"countries"|"cities"|"topics"|"build"|"ghana"|"radar";
type Row = { id?: string; title?: string|null; name?: string|null; description?: string|null; country?: string|null; country_code?: string|null; city?: string|null; location?: string|null; url?: string|null; source_url?: string|null; application_url?: string|null; official_url?: string|null; registration_url?: string|null; skills?: string[]|null; sector?: string|null; type?: string|null; starts_at?: string|null; deadline?: string|null; professional_title?: string|null; full_name?: string|null };

const configs: Record<Kind,{label:string;title:string;description:string}> = {
 jobs:{label:"Work",title:"Africa Jobs",description:"Real job and work opportunities already present in GhanaPathFinder."},
 companies:{label:"Companies",title:"African Companies",description:"Explore organizations represented by verified platform data and source-linked startup records."},
 startups:{label:"Build in Africa",title:"African Startups",description:"Source-linked startup records already available in GhanaPathFinder."},
 people:{label:"People",title:"People Building Africa",description:"Public, opted-in talent profiles from GhanaPathFinder."},
 events:{label:"Events",title:"Africa Events",description:"Real platform events with recorded dates and registration destinations."},
 countries:{label:"Live Africa",title:"Countries of Africa",description:"The country catalogue that powers country-aware discovery."},
 cities:{label:"Cities",title:"African Cities",description:"Cities represented by existing university, startup and event data."},
 topics:{label:"Discover",title:"Topics",description:"Explore the topics used to organize discovery across the platform."},
 build:{label:"Build in Africa",title:"Build in Africa",description:"Startups, funding records, investors and founder pathways already in the platform."},
 ghana:{label:"Discover Ghana",title:"Discover Ghana",description:"Ghana remains the foundation: universities, opportunities and events already in the platform."},
 radar:{label:"Opportunity Radar",title:"Opportunity Radar",description:"Active opportunities ordered by recorded deadlines. No deadlines are invented."},
};

const topics=["Artificial Intelligence","Robotics","Technology","Engineering","Science","Education","Startups","Business","Finance","Agriculture","Research","Careers","Entrepreneurship","Music","Fashion","Food","Tourism","History","Culture","Sports"];

export default function GlobalDiscovery({kind}:{kind:Kind}){
 const c=configs[kind];
 const q=useQuery({queryKey:["global-discovery",kind],queryFn:async()=>{
   if(kind==="countries"){const {data,error}=await supabase.from("africa_country_catalog").select("code,name,region,enabled").eq("enabled",true).order("name");if(error)throw error;return data as Row[];}
   if(kind==="startups"||kind==="companies"){const {data,error}=await supabase.from("african_startups").select("id,company_name,country,city,sector,stage,official_url,source_url,source_name,active_status,last_verified_at").order("company_name").limit(100);if(error)throw error;return (data??[]).map(x=>({id:x.id,name:x.company_name,country:x.country,city:x.city,sector:x.sector,type:x.stage,url:x.official_url,source_url:x.source_url}));}
   if(kind==="people"){const {data,error}=await supabase.from("talent_directory").select("user_id,full_name,professional_title,years_experience,linkedin_url,city,preferred_locations,preferred_industries,skills,bio,discoverable").eq("discoverable",true).order("full_name").limit(100);if(error)throw error;return (data??[]).map(x=>({id:x.user_id,name:x.full_name,professional_title:x.professional_title,city:x.city,skills:x.skills,description:x.bio,url:x.linkedin_url}));}
   if(kind==="events"){const {data,error}=await supabase.from("platform_events").select("id,title,type,description,starts_at,ends_at,location,is_virtual,registration_url,country").gte("starts_at",new Date().toISOString()).order("starts_at").limit(100);if(error)throw error;return (data??[]).map(x=>({id:x.id,title:x.title,type:x.type,description:x.description,starts_at:x.starts_at,location:x.location,country:x.country,url:x.registration_url}));}
   if(kind==="ghana"){const [u,o,e]=await Promise.all([supabase.from("universities").select("id,name,slug,city,region").eq("country","Ghana").order("name").limit(12),supabase.from("opportunities").select("id,title,opportunity_type,location,application_url,deadline").eq("is_active",true).eq("country_code","GH").order("deadline",{ascending:true,nullsFirst:false}).limit(12),supabase.from("platform_events").select("id,title,type,starts_at,location,registration_url").eq("country","Ghana").gte("starts_at",new Date().toISOString()).order("starts_at").limit(8)]);if(u.error)throw u.error;if(o.error)throw o.error;if(e.error)throw e.error;return [...(u.data??[]).map(x=>({id:x.id,name:x.name,city:x.city,type:"University",url:"/university/"+x.slug})),...(o.data??[]).map(x=>({id:x.id,title:x.title,type:x.opportunity_type,location:x.location,url:x.application_url,deadline:x.deadline})),...(e.data??[]).map(x=>({id:x.id,title:x.title,type:x.type,location:x.location,url:x.registration_url,starts_at:x.starts_at}))];}
   if(kind==="cities"){const [u,s,e]=await Promise.all([supabase.from("universities").select("city,country").not("city","is",null).limit(500),supabase.from("african_startups").select("city,country").not("city","is",null).limit(500),supabase.from("platform_events").select("location,country").not("location","is",null).limit(200)]);if(u.error)throw u.error;if(s.error)throw s.error;if(e.error)throw e.error;const map=new Map<string,Row>();for(const x of u.data??[]){if(x.city)map.set(x.city,{name:x.city,country:x.country});}for(const x of s.data??[]){if(x.city&&!map.has(x.city))map.set(x.city,{name:x.city,country:x.country});}for(const x of e.data??[]){if(x.location&&!map.has(x.location))map.set(x.location,{name:x.location,country:x.country});}return [...map.values()].sort((a,b)=>(a.name??"").localeCompare(b.name??"")).slice(0,150);}
   if(kind==="topics")return topics.map(name=>({name}));
   const {data,error}=await supabase.from("opportunities").select("id,title,description,opportunity_type,company_name,country_code,location,remote,application_url,source_url,source_name,deadline,created_at,is_active").eq("is_active",true).order("deadline",{ascending:true,nullsFirst:false}).limit(100);if(error)throw error;const rows=data??[];if(kind==="jobs")return rows.filter(x=>/job|employment|career|full-time|part-time|contract|freelance/i.test([x.opportunity_type,x.title,x.description].filter(Boolean).join(" ")));if(kind==="radar")return rows;return rows;
 }});
 const rows=q.data??[];
 return <div className="min-h-dvh bg-background"><Navbar/><main className="px-4 pb-14 pt-20 sm:px-8"><div className="mx-auto max-w-7xl"><p className="text-xs font-semibold uppercase tracking-[.18em] text-primary">{c.label}</p><h1 className="mt-2 text-3xl font-bold sm:text-4xl">{c.title}</h1><p className="mt-2 max-w-2xl text-sm text-muted-foreground">{c.description}</p>{kind==="topics"?<div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{rows.map((x,i)=><a key={i} href={"/search?q="+encodeURIComponent(x.name??"")} className="rounded-xl border border-border bg-card p-5 hover:bg-secondary"><h2 className="font-semibold">{x.name}</h2><p className="mt-1 text-xs text-muted-foreground">Search this topic across GhanaPathFinder</p></a>)}</div>:<div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{q.isLoading?Array.from({length:9}).map((_,i)=><div key={i} className="h-40 animate-pulse rounded-xl bg-secondary"/>):rows.map((x,i)=><article key={x.id??i} className="rounded-xl border border-border bg-card p-5"><p className="text-xs font-semibold uppercase tracking-wide text-primary">{x.type??"Discovery"}</p><h2 className="mt-1 font-semibold">{x.title??x.name??x.full_name??"Untitled record"}</h2>{x.professional_title&&<p className="mt-1 text-sm text-muted-foreground">{x.professional_title}</p>}<p className="mt-2 text-sm text-muted-foreground">{[x.country,x.country_code,x.city,x.location,x.sector].filter(Boolean).join(" · ")}</p>{x.description&&<p className="mt-3 line-clamp-3 text-sm text-muted-foreground">{x.description}</p>}{x.deadline&&<p className="mt-3 text-xs text-muted-foreground">Deadline: {new Date(x.deadline).toLocaleDateString("en-GB")}</p>}{x.starts_at&&<p className="mt-3 text-xs text-muted-foreground">{new Date(x.starts_at).toLocaleString("en-GB")}</p>}{x.skills?.length&&<div className="mt-3 flex flex-wrap gap-1">{x.skills.slice(0,6).map(s=><span key={s} className="rounded-full bg-secondary px-2 py-1 text-xs">{s}</span>)}</div>}{x.url&&<a href={x.url} target={x.url.startsWith("/")?"_self":"_blank"} rel={x.url.startsWith("/")?undefined:"noreferrer"} className="mt-4 inline-block text-sm font-medium text-primary">{x.url.startsWith("/")?"Explore":"Visit source"}</a>}</article>)}</div>}{!q.isLoading&&!rows.length&&<div className="mt-8 rounded-xl border border-dashed border-border p-10 text-center text-sm text-muted-foreground">No verified records are available for this section yet.</div>}</div></main><Footer/></div>;
}