import { useQuery } from "@tanstack/react-query";
import Navbar from "@/components/Navbar";
import { ExternalLink } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";

const HireFromAfrica=()=>{
 const people=useQuery({queryKey:["hire-africa-people"],queryFn:async()=>{const {data,error}=await supabase.from("directory_profiles").select("user_id,display_name,country,field,skills,bio,portfolio_url,linkedin_url,github_url").eq("visibility","public").limit(60);if(error)throw error;return data??[];}});
 const jobs=useQuery({queryKey:["hire-africa-jobs"],queryFn:async()=>{const {data,error}=await supabase.from("opportunities").select("id,title,company_name,organisation,country,remote,work_mode,application_url,apply_url,source_url,verified").eq("is_active",true).order("posted_at",{ascending:false}).limit(30);if(error)throw error;return data??[];}});
 return <div className="min-h-screen bg-background pt-20 pb-24"><Navbar/><main className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8"><header className="mb-8"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-primary">Global connection</p><h1 className="mt-2 text-3xl font-bold">Hire From Africa</h1><p className="mt-2 max-w-2xl text-sm text-muted-foreground">Discover professionals who explicitly chose public visibility, alongside current opportunities already stored in GhanaPathFinder.</p></header><section className="mb-9"><h2 className="mb-3 text-xl font-semibold">Discoverable professionals</h2><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{people.data?.map(x=><article key={x.user_id} className="rounded-xl border border-border bg-card p-4"><h3 className="font-semibold">{x.display_name}</h3><p className="mt-1 text-xs text-muted-foreground">{[x.field,x.country].filter(Boolean).join(" · ")}</p>{x.skills?.length&&<p className="mt-2 text-xs text-muted-foreground">{x.skills.slice(0,8).join(" · ")}</p>}{x.bio&&<p className="mt-2 text-sm text-muted-foreground line-clamp-3">{x.bio}</p>}<div className="mt-3 flex gap-3">{x.linkedin_url&&<a href={x.linkedin_url} target="_blank" rel="noreferrer" className="text-xs font-semibold text-primary">LinkedIn</a>}{x.github_url&&<a href={x.github_url} target="_blank" rel="noreferrer" className="text-xs font-semibold">GitHub</a>}{x.portfolio_url&&<a href={x.portfolio_url} target="_blank" rel="noreferrer" className="text-xs font-semibold">Portfolio</a>}</div></article>)}</div>{!people.isLoading&&!people.data?.length&&<div className="rounded-xl border border-dashed border-border p-6 text-sm text-muted-foreground">No public professional profiles are currently available.</div>}</section><section><h2 className="mb-3 text-xl font-semibold">Current work opportunities</h2><div className="grid gap-3 md:grid-cols-2">{jobs.data?.map(x=><article key={x.id} className="rounded-xl border border-border bg-card p-4"><h3 className="font-semibold">{x.title}</h3><p className="mt-1 text-xs text-muted-foreground">{x.company_name||x.organisation||"Organisation"} · {x.country||"Africa"}{x.remote||x.work_mode==="Remote"?" · Remote":""}</p>{(x.apply_url||x.application_url||x.source_url)&&<a href={x.apply_url||x.application_url||x.source_url||"#"} target="_blank" rel="noreferrer" className="mt-3 inline-flex items-center gap-1 text-xs font-semibold text-primary">Open opportunity <ExternalLink className="h-3.5 w-3.5"/></a>}</article>)}</div></section></main></div>;
};
export default HireFromAfrica;
