
import { useQuery } from "@tanstack/react-query";
import Navbar from "@/components/Navbar";
import Seo from "@/components/Seo";
import { ExternalLink, MapPin } from "@/lib/icons";
import { supabase } from "@/integrations/supabase/client";

export default function InternationalCommunity(){
  const q=useQuery({queryKey:["embassies"],queryFn:async function(){const r=await supabase.from("embassies").select("*").order("represents_country");if(r.error)throw r.error;return r.data||[];}});
  return <div className="min-h-dvh bg-background"><Navbar/><main className="mx-auto max-w-6xl px-4 pb-24 pt-20 sm:px-6 lg:px-8"><Seo title="International Community | GhanaPathFinder" description="Embassy and high commission information for students planning international study from Ghana." path="/international-community"/><header className="border-b border-border pb-7"><p className="text-sm font-semibold text-primary">International Community</p><h1 className="mt-2 text-3xl font-bold">Official missions, sourced directly.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">Head-of-mission names remain blank until independently verified against a current official source.</p></header><div className="mt-7 grid gap-3 md:grid-cols-2 lg:grid-cols-3">{(q.data||[]).map(function(x){return <article key={x.id} className="border border-border bg-card p-5"><h2 className="font-semibold">{x.represents_country}</h2><p className="mt-1 text-xs text-primary">{x.mission_type} · {x.represents_country_code}</p>{x.address&&<p className="mt-3 flex gap-2 text-sm text-muted-foreground"><MapPin className="h-4 w-4 shrink-0"/>{x.address}</p>}<div className="mt-4 flex flex-wrap gap-3 text-xs">{x.official_website&&<a href={x.official_website} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-primary">Official site <ExternalLink className="h-3.5 w-3.5"/></a>}{x.visa_info_url&&<a href={x.visa_info_url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-primary">Visa information <ExternalLink className="h-3.5 w-3.5"/></a>}</div>{x.last_verified&&<p className="mt-3 text-[11px] text-muted-foreground">Last verified {x.last_verified}</p>}</article>;})}</div>{!q.isLoading && !(q.data||[]).length&&<div className="mt-6 border border-dashed border-border p-6 text-sm text-muted-foreground">Embassy research data is not imported yet.</div>}</main></div>
}
