import { useEffect, useMemo, useState } from "react";
import { ExternalLink, Globe, GraduationCap, Search, ShieldCheck } from "@/lib/icons";
import Navbar from "@/components/Navbar";
import Seo from "@/components/Seo";
import { supabase } from "@/integrations/supabase/client";

type Qualification={country_code:string;country_name:string;qualification_code:string;qualification_name:string;level:string;notes:string|null;source_url:string|null};
type GradingScale={qualification_code:string;scale_min:number;scale_max:number;pass_mark:number|null;grade_notes:string|null;ghana_interpretation:string;source_url:string|null;verification_status:string};
type Rule={institution_id:string;minimum_overall_score:number|null;score_operator:string|null;equivalency_required:boolean;english_proficiency_required:boolean;notes:string|null;source_url:string;verification_status?:string;universities?:{name:string;short_name:string|null}|null};
type Programme={id:string;name:string;slug:string;field:string|null;degree_type:string|null;entry_requirements:string|null;university_id:string|null;institution_id:string|null;verification_status:string|null;source_url:string|null;universities?:{name:string;short_name:string|null}|null};

const InternationalPathway=()=>{
 const[country,setCountry]=useState("");const[qualificationCode,setQualificationCode]=useState("");const[field,setField]=useState("");const[score,setScore]=useState("");const[loading,setLoading]=useState(false);const[gradingScale,setGradingScale]=useState<GradingScale|null>(null);const[message,setMessage]=useState("");const[qualifications,setQualifications]=useState<Qualification[]>([]);const[rules,setRules]=useState<Rule[]>([]);const[programmes,setProgrammes]=useState<Programme[]>([]);const[estimated,setEstimated]=useState(false);const[submitted,setSubmitted]=useState(false);
 useEffect(()=>{supabase.from("international_qualification_catalog").select("country_code,country_name,qualification_code,qualification_name,level,notes,source_url").order("country_name").then(({data,error})=>{if(error){console.error(error);setMessage("We could not load qualification options. Please try again.");return;}setQualifications((data??[]) as Qualification[]);});},[]);
 useEffect(()=>{setGradingScale(null);if(!qualificationCode)return;supabase.from("international_grading_scales").select("qualification_code,scale_min,scale_max,pass_mark,grade_notes,ghana_interpretation,source_url,verification_status").eq("qualification_code",qualificationCode).maybeSingle().then(({data,error})=>{if(error){console.error(error);return;}setGradingScale((data??null) as GradingScale|null);});},[qualificationCode]);
 const countries=useMemo(()=>[...new Map(qualifications.map(q=>[q.country_code,q.country_name])).entries()],[qualifications]);
 const available=useMemo(()=>qualifications.filter(q=>q.country_code===country||q.country_code==="INT"),[qualifications,country]);
 const selected=qualifications.find(q=>q.qualification_code===qualificationCode);
 const evaluate=async()=>{if(!country||!qualificationCode){setMessage("Choose your country and qualification first.");return;}setLoading(true);setSubmitted(true);setMessage("");try{
   const{data:rr,error:re}=await supabase.from("international_pathway_rules").select("institution_id,minimum_overall_score,score_operator,equivalency_required,english_proficiency_required,notes,source_url,universities(name,short_name)").eq("qualification_code",qualificationCode).eq("academic_level","undergraduate");if(re)throw re;
   let rs=(rr??[]) as unknown as Rule[];
   let isEstimated=false;
   if(!rs.length){
     const{data:fr,error:fe}=await supabase.from("international_pathway_rules").select("institution_id,minimum_overall_score,score_operator,equivalency_required,english_proficiency_required,notes,source_url,verification_status,universities(name,short_name)").eq("academic_level","undergraduate").limit(50);
     if(fe)throw fe;
     const fallback=(fr??[]) as unknown as Rule[];
     rs=fallback.map(r=>({...r,minimum_overall_score:null,score_operator:null,notes:r.notes?("Estimated from a published international qualification pathway. "+r.notes):"Estimated from a published international qualification pathway."}));
     isEstimated=rs.length>0;
   }
   setEstimated(isEstimated);setRules(rs);const ids=rs.map(r=>r.institution_id);
   if(!ids.length){setProgrammes([]);setMessage("We do not have a verified pathway rule for this qualification yet. You can still explore Ghanaian study options, but no estimate is available yet.");return;}
   const programmeSelect="id,name,slug,field,degree_type,entry_requirements,university_id,institution_id,verification_status,source_url,universities(name,short_name)";
   const[{data:byUniversity,error:ue},{data:byInstitution,error:ie}]=await Promise.all([
     supabase.from("programmes").select(programmeSelect).in("university_id",ids).limit(250),
     supabase.from("programmes").select(programmeSelect).in("institution_id",ids).limit(250)
   ]);
   if(ue)throw ue;if(ie)throw ie;
   const merged=new Map<string,unknown>();
   [...(byUniversity??[]),...(byInstitution??[])].forEach(p=>merged.set((p as {id:string}).id,p));
   let rows=[...merged.values()] as unknown as Programme[];
   if(field.trim())rows=rows.filter(p=>(p.field??"").toLowerCase().includes(field.trim().toLowerCase()));
   const n=Number(score);
   const filtered=score.trim()&&Number.isFinite(n)?rows.filter(p=>{
     const ruleInstitutionId=p.university_id??p.institution_id;
     const r=rs.find(x=>x.institution_id===ruleInstitutionId);
     if(!r||r.minimum_overall_score==null||!r.score_operator)return true;
     return r.score_operator==="<= "?n<=r.minimum_overall_score:n>=r.minimum_overall_score;
   }):rows;
   setProgrammes(filtered);
 }catch(e){console.error(e);setMessage("We could not evaluate this pathway. Please try again.");}finally{setLoading(false);}};
 const input="w-full px-4 py-3 rounded-lg bg-secondary border border-border text-foreground text-sm focus:outline-hidden focus:ring-2 focus:ring-primary/50";const card="bg-glass rounded-xl border border-border/60 p-5";
 return <div className="min-h-screen bg-background px-4 sm:px-8 lg:px-12 pt-20 pb-12"><Seo title="International Student Pathway | GhanaPathFinder" description="Explore verified pathways from international qualifications into Ghanaian universities and programmes." path="/international-pathway"/><Navbar/><div className="max-w-6xl mx-auto">
 <section className="max-w-3xl mb-8"><div className="inline-flex items-center gap-2 text-sm text-primary font-medium mb-3"><Globe className="h-4 w-4"/> Study in Ghana</div><h1 className="font-display text-3xl sm:text-5xl font-bold text-foreground mb-3">Find your pathway to Ghana</h1><p className="text-sm sm:text-base text-muted-foreground">Choose your country and qualification. GhanaPathFinder checks verified institutional rules and then surfaces relevant Ghanaian programmes.</p></section>
 <section className={card}><div className="grid gap-4 md:grid-cols-2">
 <label className="text-sm text-foreground"><span className="block mb-1.5 font-medium">1. Country</span><select className={input} value={country} onChange={e=>{setCountry(e.target.value);setQualificationCode("");setSubmitted(false)}}><option value="">Select country</option>{countries.map(([c,n])=><option key={c} value={c}>{n}</option>)}</select></label>
 <label className="text-sm text-foreground"><span className="block mb-1.5 font-medium">2. Qualification</span><select className={input} value={qualificationCode} disabled={!country} onChange={e=>{setQualificationCode(e.target.value);setSubmitted(false)}}><option value="">{country?"Select qualification":"Select country first"}</option>{available.map(q=><option key={q.qualification_code} value={q.qualification_code}>{q.qualification_name}</option>)}</select></label>
 <label className="text-sm text-foreground"><span className="block mb-1.5 font-medium">3. Intended field</span><input className={input} value={field} onChange={e=>setField(e.target.value)} placeholder="e.g. Computer Science"/></label>
 {(selected?.qualification_code==="WASSCE"||selected?.qualification_code==="AMERICAN_HS"||gradingScale)&&<label className="text-sm text-foreground"><span className="block mb-1.5 font-medium">{gradingScale?`Your result (${gradingScale.scale_min}–${gradingScale.scale_max})`:selected?.qualification_code==="WASSCE"?"Overall aggregate":"Final grade point"}</span><input className={input} value={score} onChange={e=>setScore(e.target.value)} inputMode="decimal" placeholder={gradingScale?`e.g. ${gradingScale.pass_mark??gradingScale.scale_min}`:selected?.qualification_code==="WASSCE"?"e.g. 18":"e.g. 3.2"}/></label>}
 </div>{selected?.notes&&<p className="text-xs text-muted-foreground mt-4">{selected.notes}</p>}{gradingScale&&<div className="mt-4 rounded-lg border border-border/60 bg-secondary/40 p-4"><p className="text-sm font-medium text-foreground">How your result is interpreted</p><p className="text-xs text-muted-foreground mt-1">{gradingScale.grade_notes}</p><p className="text-xs text-muted-foreground mt-2">{gradingScale.ghana_interpretation}</p>{score.trim()&&Number.isFinite(Number(score))&&<p className="text-xs text-foreground mt-3 font-medium">Normalized planning score: {Math.max(0,Math.min(100,((Number(score)-gradingScale.scale_min)/(gradingScale.scale_max-gradingScale.scale_min))*100)).toFixed(1)}%</p>}</div>}<button onClick={evaluate} disabled={loading} className="mt-5 inline-flex items-center gap-2 px-5 py-3 rounded-lg bg-primary text-primary-foreground text-sm font-semibold"><Search className="h-4 w-4"/>{loading?"Evaluating pathway…":"Evaluate my pathway"}</button></section>
 {message&&<p className="mt-5 text-sm text-muted-foreground">{message}</p>}
 {submitted&&!loading&&rules.length>0&&<section className="mt-8 space-y-4"><div><h2 className="font-display text-2xl font-bold text-foreground">Your Ghana pathway</h2><p className="text-sm text-muted-foreground mt-1">{estimated?"No verified rule exists for this qualification yet. The results below are estimates based on published international qualification pathways and are not official eligibility decisions.":`Verified institutional pathway rules found: ${rules.length}. Programme-level requirements still apply.`}</p></div>
 <div className="grid gap-4 md:grid-cols-2">{rules.map(r=><article key={r.institution_id} className={card}><div className="flex items-start gap-3"><div className="p-2 rounded-lg bg-secondary"><GraduationCap className="h-5 w-5 text-primary"/></div><div><h3 className="font-semibold text-foreground">{r.universities?.short_name||r.universities?.name}</h3><p className="text-xs text-muted-foreground mt-1">{estimated?"Estimated pathway · not officially verified":r.minimum_overall_score!=null?"Published threshold: "+r.minimum_overall_score+" "+r.score_operator:"Programme-specific assessment"}</p></div></div>{r.equivalency_required&&<p className="text-xs text-muted-foreground mt-3">Formal equivalence or institutional assessment may still be required.</p>}{r.english_proficiency_required&&<p className="text-xs text-muted-foreground mt-2">English proficiency evidence may be required.</p>}{r.notes&&<p className="text-xs text-muted-foreground mt-3">{r.notes}</p>}<a href={r.source_url} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1.5 text-xs text-primary mt-4">Verify on official source <ExternalLink className="h-3 w-3"/></a></article>)}</div>
 <div className={card}><h3 className="font-display text-xl font-semibold text-foreground mb-1">Discover programmes</h3><p className="text-xs text-muted-foreground mb-4">{estimated?"These programmes are connected to institutions with published international pathway information. Because this qualification has no verified rule in GhanaPathFinder yet, these are estimates only. Confirm eligibility with the institution before applying.":"These programmes are connected to institutions with verified pathway rules. This is not a programme-level admission guarantee."}</p>{programmes.length?<div className="grid gap-3 md:grid-cols-2">{programmes.map(p=><a key={p.id} href={"/programme/"+p.slug} className="rounded-lg border border-border/60 p-4 hover:border-primary/50"><p className="font-medium text-foreground">{p.name}</p><p className="text-xs text-muted-foreground mt-1">{p.universities?.short_name||p.universities?.name}{p.degree_type?" · "+p.degree_type:""}</p>{p.entry_requirements&&<p className="text-xs text-muted-foreground mt-2 line-clamp-2">{p.entry_requirements}</p>}</a>)}</div>:<p className="text-sm text-muted-foreground">No matching programmes were found. Try a broader field.</p>}</div></section>}
 <div className="mt-8 rounded-xl border border-border/60 p-5"><h3 className="font-semibold text-foreground">Important for international applicants</h3><p className="text-xs text-muted-foreground mt-2">A grading-scale normalization helps compare results consistently, but it does not create an official Ghanaian equivalence. GTEC evaluates foreign credentials and can issue an equivalence assessment. Universities may also apply their own subject, language, and programme requirements.</p><div className="mt-3 flex flex-wrap gap-3 text-xs"><a href="https://cems.gtec.edu.gh/" target="_blank" rel="noopener noreferrer" className="text-primary inline-flex items-center gap-1.5">Check credential evaluation <ExternalLink className="h-3 w-3"/></a></div></div><div className="mt-8 flex gap-3 text-xs text-muted-foreground"><ShieldCheck className="h-4 w-4 shrink-0 text-primary"/><p>{estimated?"This qualification does not yet have a verified pathway rule in GhanaPathFinder. Estimates are generated from available published international pathway information and can be wrong or incomplete. Confirm the exact requirement directly with the institution before applying or paying any fees.":"Rules are sourced from official institutional pages and can change. Results are a planning aid, not an admission decision."}</p></div>
 </div></div>;
};
export default InternationalPathway;
