import { useQuery } from "@tanstack/react-query";
import Navbar from "@/components/Navbar";
import { ExternalLink } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";

const NewsHub=({title="Africa Now",subtitle="Current Africa stories already available in GhanaPathFinder, with the original source preserved."}:{title?:string;subtitle?:string})=>{
 const q=useQuery({queryKey:["news-hub"],queryFn:async()=>{const {data,error}=await supabase.from("news_articles").select("id,title,excerpt,original_url,country_code,category,published_at,source_name").order("published_at",{ascending:false}).limit(40);if(error)throw error;return data??[];}});
 return <div className="min-h-screen bg-background pt-20 pb-24"><Navbar/><main className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8"><header className="mb-7"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-primary">Africa news</p><h1 className="mt-2 text-3xl font-bold">{title}</h1><p className="mt-2 max-w-2xl text-sm text-muted-foreground">{subtitle}</p></header><div className="grid gap-3 md:grid-cols-2">{q.data?.map(x=><article key={x.id} className="rounded-xl border border-border bg-card p-4"><div className="flex items-center justify-between gap-3"><span className="text-[11px] uppercase tracking-wide text-primary">{x.category||"Africa"}</span><span className="text-[11px] text-muted-foreground">{x.published_at?new Date(x.published_at).toLocaleDateString():""}</span></div><h2 className="mt-2 font-semibold">{x.title}</h2>{x.excerpt&&<p className="mt-2 text-sm text-muted-foreground line-clamp-3">{x.excerpt}</p>}<p className="mt-3 text-xs text-muted-foreground">{x.source_name||"Source"}{x.country_code?" · "+x.country_code:""}</p>{x.original_url&&<a href={x.original_url} target="_blank" rel="noreferrer" className="mt-3 inline-flex items-center gap-1.5 text-xs font-semibold text-primary">Read source <ExternalLink className="h-3.5 w-3.5"/></a>}</article>)}</div>{!q.isLoading&&!q.data?.length&&<div className="rounded-xl border border-dashed border-border p-6 text-sm text-muted-foreground">No published news records are currently available.</div>}</main></div>;
};
export default NewsHub;
