import { useEffect, useMemo, useState } from "react";
import { ExternalLink, MapPin, CalendarClock, Search, BookOpen, Briefcase, Newspaper } from "@/lib/icons";
import Navbar from "@/components/Navbar";
import { supabase } from "@/integrations/supabase/client";

type Job = { id:string; title:string; opportunity_type:string|null; country_code:string|null; location:string|null; remote:boolean|null; description:string|null; skills:string[]|null; application_url:string|null; source_name:string|null; source_url:string|null; deadline:string|null; companies?: { name:string }|null };
type News = { id:string; title:string; excerpt:string|null; original_url:string; category:string|null; published_at:string|null; country_code:string|null };

export default function Opportunities(){
 const [jobs,setJobs]=useState<Job[]>([]); const [news,setNews]=useState<News[]>([]);
 const [query,setQuery]=useState(""); const [type,setType]=useState("all"); const [tab,setTab]=useState<"jobs"|"news"|"student">("jobs"); const [loading,setLoading]=useState(true);
 useEffect(()=>{let cancelled=false;(async()=>{
  const [j,n]=await Promise.all([
   (supabase.from("opportunities" as never) as any).select("id,title,opportunity_type,country_code,location,remote,description,skills,application_url,source_name,source_url,deadline,companies(name)").eq("status","active").order("created_at",{ascending:false}).limit(80),
   (supabase.from("news_articles" as never) as any).select("id,title,excerpt,original_url,category,published_at,country_code").order("published_at",{ascending:false}).limit(40)
  ]);
  if(!cancelled){setJobs(j.data??[]);setNews(n.data??[]);setLoading(false);}
 })();return()=>{cancelled=true}},[]);
 const types=useMemo(()=>Array.from(new Set(jobs.map(x=>x.opportunity_type).filter(Boolean))) as string[],[jobs]);
 const filtered=useMemo(()=>{const q=query.toLowerCase().trim();return jobs.filter(j=>(type==="all"||j.opportunity_type===type)&&(!q||[j.title,j.description,j.country_code,j.companies?.name,...(j.skills??[])].filter(Boolean).join(" ").toLowerCase().includes(q)))},[jobs,type,query]);
 return <div className="min-h-screen bg-background text-foreground"><Navbar/><main className="mx-auto max-w-7xl px-4 pt-20 pb-20 sm:px-6 lg:px-8">
  <p className="text-sm font-semibold uppercase tracking-wide text-primary">Africa opportunity feed</p>
  <h1 className="mt-2 text-3xl font-bold sm:text-4xl">Work, news and learning</h1>
  <p className="mt-3 max-w-3xl text-muted-foreground">A single feed for corporate jobs, internships, African startup news and useful student resources. Listings retain their source and application link.</p>
  <div className="mt-6 flex flex-wrap gap-2">
   {([["jobs","Jobs & internships",Briefcase],["news","Africa startup news",Newspaper],["student","Student world",BookOpen]] as const).map(([v,label,Icon])=><button key={v} onClick={()=>setTab(v)} className={`inline-flex items-center gap-2 rounded-lg px-4 py-2.5 text-sm font-semibold ${tab===v?"bg-primary text-primary-foreground":"border border-border bg-card"}`}><Icon className="h-4 w-4"/>{label}</button>)}
  </div>
  {tab==="jobs" && <><div className="mt-6 grid gap-3 md:grid-cols-[1fr_200px]"><label className="flex items-center gap-2 rounded-lg border border-border bg-card px-3"><Search className="h-4 w-4 text-muted-foreground"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search role, employer or skill" className="h-11 w-full bg-transparent text-sm outline-none"/></label><select value={type} onChange={e=>setType(e.target.value)} className="h-11 rounded-lg border border-border bg-card px-3 text-sm"><option value="all">All opportunity types</option>{types.map(t=><option key={t}>{t}</option>)}</select></div>
  <div className="mt-7 grid gap-4 lg:grid-cols-2">{loading?<div className="py-12 text-sm text-muted-foreground">Loading opportunities...</div>:filtered.length?filtered.map(item=><article key={item.id} className="rounded-xl border border-border bg-card p-5"><div className="flex items-start justify-between gap-4"><div><h2 className="font-semibold">{item.title}</h2><p className="mt-1 text-sm text-muted-foreground">{item.companies?.name||"Employer"}{item.opportunity_type?` · ${item.opportunity_type}`:""}</p></div>{item.remote&&<span className="rounded-full bg-primary/10 px-2.5 py-1 text-xs text-primary">Remote</span>}</div><div className="mt-3 flex flex-wrap gap-3 text-xs text-muted-foreground">{(item.location||item.country_code)&&<span className="inline-flex items-center gap-1"><MapPin className="h-3.5 w-3.5"/>{item.location||item.country_code}</span>}{item.deadline&&<span className="inline-flex items-center gap-1"><CalendarClock className="h-3.5 w-3.5"/>Deadline {new Date(item.deadline).toLocaleDateString("en-GB")}</span>}</div>{item.description&&<p className="mt-4 line-clamp-3 text-sm leading-6 text-muted-foreground">{item.description}</p>}<div className="mt-4 flex flex-wrap gap-1.5">{(item.skills??[]).slice(0,7).map(s=><span key={s} className="rounded-md border border-border px-2 py-1 text-xs">{s}</span>)}</div><div className="mt-5 flex gap-2"><a href={item.application_url||item.source_url||"#"} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground">Apply <ExternalLink className="h-4 w-4"/></a>{item.source_url&&<a href={item.source_url} target="_blank" rel="noreferrer" className="rounded-lg border border-border px-4 py-2.5 text-sm">{item.source_name||"Source"}</a>}</div></article>):<div className="rounded-xl border border-dashed border-border p-10 text-sm text-muted-foreground lg:col-span-2">No matching active opportunities yet. Complete your profile to improve future matching.</div>}</div></>}
  {tab==="news" && <div className="mt-7 grid gap-4 md:grid-cols-2">{news.map(item=><article key={item.id} className="rounded-xl border border-border bg-card p-5"><p className="text-xs uppercase tracking-wide text-primary">{item.category||"Africa"}</p><h2 className="mt-2 font-semibold">{item.title}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{item.excerpt||"Read the original report."}</p><div className="mt-4 flex items-center justify-between gap-3 text-xs text-muted-foreground"><span>{item.published_at?new Date(item.published_at).toLocaleString("en-GB"):"Recently updated"}</span><a href={item.original_url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-primary">Read source <ExternalLink className="h-3.5 w-3.5"/></a></div></article>)}</div>}
  {tab==="student" && <div className="mt-7 grid gap-4 md:grid-cols-3">{[["Learning resources","Courses, research methods, programming, AI and professional skills.","/skills"],["Career discovery","Explore careers, pathways and the skills behind them.","/careers"],["Innovation","Discover African startups, projects and builders through the community.","/community"]].map(([title,desc,to])=><a key={title} href={to} className="rounded-xl border border-border bg-card p-6"><h2 className="font-semibold">{title}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{desc}</p><span className="mt-5 inline-flex text-sm font-semibold text-primary">Explore <ExternalLink className="ml-1 h-4 w-4"/></span></a>)}</div>}
  <p className="mt-8 text-xs text-muted-foreground">News refresh is configured for hourly ingestion. LinkedIn is supported as a profile/source connection; direct LinkedIn job-data access requires LinkedIn-approved API access.</p>
 </main></div>;
}