import { useEffect,useMemo,useState } from "react";
import { Link } from "@tanstack/react-router";
import { supabase } from "@/integrations/supabase/client";
import Navbar from "@/components/Navbar";
import { Search,ExternalLink,MapPin,Clock3 } from "@/lib/icons";
type Opportunity={id:string;title:string;opportunity_type:string|null;company_name:string|null;country_code:string|null;location:string|null;city:string|null;remote:boolean|null;description:string|null;skills:string[]|null;application_url:string|null;source_name:string|null;source_url:string|null;deadline:string|null};
export default function Opportunities(){
const [items,setItems]=useState<Opportunity[]>([]),[q,setQ]=useState(""),[type,setType]=useState("all"),[remote,setRemote]=useState(false),[loading,setLoading]=useState(true);
useEffect(()=>{let active=true;(async()=>{const r=await supabase.from("opportunities").select("id,title,opportunity_type,company_name,country_code,location,city,remote,description,skills,application_url,source_name,source_url,deadline").eq("status","active").order("created_at",{ascending:false}).limit(60);if(active){if(!r.error)setItems((r.data||[]) as Opportunity[]);setLoading(false)}})();return()=>{active=false}},[]);
const types=Array.from(new Set(items.map(x=>x.opportunity_type).filter(Boolean))) as string[];
const filtered=useMemo(()=>items.filter(o=>{const hay=[o.title,o.company_name,o.description,o.country_code,...(o.skills||[])].filter(Boolean).join(" ").toLowerCase();return(!q||hay.includes(q.toLowerCase()))&&(type==="all"||o.opportunity_type===type)&&(!remote||o.remote===true)}),[items,q,type,remote]);
return <div className="min-h-screen bg-background"><Navbar/><main className="mx-auto max-w-7xl px-4 pb-20 pt-20 sm:px-6 lg:px-8"><div className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-wide text-primary">Opportunity hub</p><h1 className="mt-2 text-3xl font-bold sm:text-4xl">Jobs, internships and opportunities</h1><p className="mt-3 text-muted-foreground">A unified feed using verified records stored in GhanaPathFinder. Each listing keeps its source and application link.</p></div>
<div className="mt-7 grid gap-3 md:grid-cols-[1fr_200px_auto]"><label className="flex items-center gap-2 rounded-lg border border-border bg-card px-3"><Search className="h-4 w-4 text-muted-foreground"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search title, company or skill" className="h-11 w-full bg-transparent text-sm outline-none"/></label><select value={type} onChange={e=>setType(e.target.value)} className="h-11 rounded-lg border border-border bg-card px-3 text-sm"><option value="all">All types</option>{types.map(t=><option key={t} value={t}>{t}</option>)}</select><label className="inline-flex h-11 items-center gap-2 rounded-lg border border-border bg-card px-4 text-sm"><input type="checkbox" checked={remote} onChange={e=>setRemote(e.target.checked)}/> Remote only</label></div>
<div className="mt-8 grid gap-4 lg:grid-cols-2">{loading?<div className="py-12 text-sm text-muted-foreground">Loading opportunities...</div>:filtered.length?filtered.map(o=><article key={o.id} className="rounded-xl border border-border bg-card p-5"><div className="flex items-start justify-between gap-4"><div><h2 className="font-semibold">{o.title}</h2><p className="mt-1 text-sm text-muted-foreground">{o.company_name||"Organization"}{o.opportunity_type?" · "+o.opportunity_type:""}</p></div>{o.remote&&<span className="rounded-full bg-primary/10 px-2.5 py-1 text-xs font-medium text-primary">Remote</span>}</div><div className="mt-3 flex flex-wrap gap-3 text-xs text-muted-foreground">{(o.city||o.location||o.country_code)&&<span className="inline-flex items-center gap-1"><MapPin className="h-3.5 w-3.5"/>{o.city||o.location||o.country_code}</span>}{o.deadline&&<span className="inline-flex items-center gap-1"><Clock3 className="h-3.5 w-3.5"/>Deadline {new Date(o.deadline).toLocaleDateString("en-GB")}</span>}</div>{o.description&&<p className="mt-4 line-clamp-3 text-sm leading-6 text-muted-foreground">{o.description}</p>}{!!o.skills?.length&&<div className="mt-4 flex flex-wrap gap-1.5">{o.skills.slice(0,6).map(s=><span key={s} className="rounded-md border border-border px-2 py-1 text-xs">{s}</span>)}</div>}<div className="mt-5 flex flex-wrap gap-2"><a href={o.application_url||o.source_url||"#"} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground">Apply <ExternalLink className="h-4 w-4"/></a>{o.source_url&&<a href={o.source_url} target="_blank" rel="noreferrer" className="rounded-lg border border-border px-4 py-2.5 text-sm font-medium">{o.source_name||"Source"}</a>}</div></article>):<div className="rounded-xl border border-dashed border-border p-10 text-sm text-muted-foreground lg:col-span-2">No matching active opportunities yet.</div>}</div><p className="mt-8 text-xs text-muted-foreground"><Link to="/onboarding" className="text-primary">Complete your profile</Link> to make future opportunity matching more relevant.</p></main></div>}
}