import { useMemo, useState } from "react";
import { Link } from "@tanstack/react-router";
import { ArrowRight, BookOpen, BriefcaseBusiness, CheckCircle2, CircleDollarSign, ClipboardCheck, GraduationCap, Lightbulb, Map, Target, TrendingUp, Trophy, WalletCards } from "lucide-react";

const skills = [["Python", "Foundation", 70], ["Git & GitHub", "Foundation", 55], ["Data Structures", "Intermediate", 25], ["Machine Learning", "Intermediate", 10], ["Linear Algebra", "Foundation", 35], ["Cloud & Deployment", "Intermediate", 15]] as const;
const projects = [["Beginner", "Personal portfolio", "Public portfolio + GitHub evidence", "1–2 weeks"], ["Intermediate", "Recommendation system", "End-to-end data/ML project", "2–4 weeks"], ["Advanced", "AI-powered application", "Deployed product with measurable users", "4–8 weeks"] as const;
const opportunities = [["Internship", "Find internships matching your target career", "/internships"], ["Scholarship", "Find funding before an application deadline", "/scholarships"], ["Community", "Connect with students and share experiences", "/community"], ["Research", "Explore research and build evidence for graduate study", "/careers"] as const;
const routes = ["Define target", "Compare programmes", "Secure funding", "Build skills", "Build evidence", "Get experience"];
const tasks = ["Complete your career goal", "Shortlist 3 realistic programmes", "Review scholarships that match you", "Choose your next skill", "Start your first portfolio project"];

export default function PathOS() {
  const [goal, setGoal] = useState("AI Engineer");
  const [budget, setBudget] = useState("low");
  const [tab, setTab] = useState("Overview");
  const [done, setDone] = useState<Record<number, boolean>>({});
  const [monthly, setMonthly] = useState(1200);
  const fit = useMemo(() => Math.min(85 + (goal.trim() ? 5 : 0) + (budget === "low" ? 3 : 0), 95), [goal, budget]);
  const completed = Object.values(done).filter(Boolean).length;

  return <section className="rounded-2xl border border-border bg-glass p-5 sm:p-7">
    <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between">
      <div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-primary">Path OS</p><h2 className="font-display text-2xl sm:text-3xl font-bold mt-2">Turn your goal into an executable path.</h2><p className="text-sm text-muted-foreground mt-2 max-w-2xl">One planning layer connecting education, funding, skills, projects, applications and opportunities.</p></div>
      <div className="min-w-[180px] rounded-xl border border-border bg-secondary/50 p-4"><div className="flex justify-between text-xs text-muted-foreground"><span>Path fit</span><strong className="text-foreground">{fit}%</strong></div><div className="mt-2 h-2 rounded-full bg-background overflow-hidden"><div className="h-full rounded-full bg-primary" style={{ width: `${fit}%` }} /></div></div>
    </div>

    <div className="mt-6 flex gap-1 overflow-x-auto border-b border-border">{["Overview", "Applications", "Funding", "Skills", "Projects", "Opportunities"].map(x => <button key={x} onClick={() => setTab(x)} className={`whitespace-nowrap border-b-2 px-3 py-3 text-sm font-medium ${tab === x ? "border-primary text-foreground" : "border-transparent text-muted-foreground"}`}>{x}</button>)}</div>

    {tab === "Overview" && <div className="mt-6 space-y-5"><div className="grid gap-4 lg:grid-cols-[1.4fr_.8fr]"><div className="rounded-xl border border-border p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-xs text-muted-foreground">Destination</p><h3 className="text-xl font-semibold mt-1">{goal || "Choose a career"}</h3></div><Target className="h-5 w-5 text-primary" /></div><label className="block mt-5 text-sm font-medium">Target career<input value={goal} onChange={e => setGoal(e.target.value)} className="mt-2 w-full rounded-lg border border-border bg-background px-3 py-2.5" placeholder="e.g. AI Engineer" /></label><label className="block mt-4 text-sm font-medium">Financial priority<select value={budget} onChange={e => setBudget(e.target.value)} className="mt-2 w-full rounded-lg border border-border bg-background px-3 py-2.5"><option value="low">Minimize cost</option><option value="medium">Moderate budget</option><option value="high">Flexible budget</option></select></label><p className="mt-3 text-xs text-muted-foreground">Planning inputs are kept in this session. Full account persistence can be connected to the existing profile tables.</p></div><div className="rounded-xl border border-border p-5"><p className="text-xs uppercase tracking-wide text-muted-foreground">Route</p><ol className="mt-4 space-y-3">{routes.map((x,i) => <li key={x} className="flex gap-3 text-sm"><span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full border border-border text-xs">{i+1}</span><span className={i === 0 ? "font-medium" : "text-muted-foreground"}>{x}</span></li>)}</ol></div></div><div className="grid gap-4 md:grid-cols-5">{[[GraduationCap,"University"],[WalletCards,"Funding"],[BookOpen,"Skills"],[Lightbulb,"Projects"],[BriefcaseBusiness,"Experience"]].map(([I,l]) => { const Icon = I as typeof Target; return <div key={String(l)} className="rounded-xl border border-border p-4"><Icon className="h-4 w-4 text-primary mb-3"/><p className="text-xs font-medium">{String(l)}</p></div>; })}</div><div className="rounded-xl border border-border p-5"><div className="flex justify-between"><div><h3 className="font-semibold">Next 30 days</h3><p className="text-sm text-muted-foreground">Actions that move the plan forward.</p></div><span className="text-sm text-muted-foreground">{completed}/{tasks.length}</span></div><div className="grid gap-2 mt-4 md:grid-cols-2">{tasks.map((x,i) => <button key={x} onClick={() => setDone(d => ({...d,[i]:!d[i]}))} className="flex items-center gap-3 rounded-lg border border-border p-3 text-left"><CheckCircle2 className={`h-5 w-5 ${done[i] ? "text-primary" : "text-muted-foreground"}`} /><span className={`text-sm ${done[i] ? "line-through text-muted-foreground" : "font-medium"}`}>{x}</span></button>)}</div></div></div>}

    {tab === "Applications" && <div className="mt-6 space-y-4"><div className="grid gap-3 md:grid-cols-3">{[["Preparing","Choose programmes and gather documents"],["Submitted","Track decisions and follow-ups"],["Deadlines","Never lose the next action"]].map(([x,y]) => <Link key={x} to="/applications" className="rounded-xl border border-border p-5 hover:bg-muted/30"><ClipboardCheck className="h-5 w-5 text-primary"/><h3 className="font-semibold mt-3">{x}</h3><p className="text-sm text-muted-foreground mt-1">{y}</p><span className="inline-flex items-center gap-1 mt-4 text-sm font-medium">Open tracker <ArrowRight className="h-4 w-4"/></span></Link>)}</div><div className="rounded-xl border border-border p-5"><h3 className="font-semibold">Application evidence checklist</h3><div className="grid gap-2 sm:grid-cols-2 mt-4">{["WASSCE results", "Identity document", "Programme requirements", "Reference/recommendation", "Personal statement where required", "Application fee where required"].map(x => <div key={x} className="flex gap-2 items-center border border-border rounded-lg p-3 text-sm"><CheckCircle2 className="h-4 w-4 text-muted-foreground"/>{x}</div>)}</div></div></div>}

    {tab === "Funding" && <div className="mt-6 grid gap-4 lg:grid-cols-2"><div className="rounded-xl border border-border p-5"><div className="flex gap-2 items-center"><CircleDollarSign className="h-5 w-5 text-primary"/><h3 className="font-semibold">True cost planner</h3></div><div className="grid gap-3 sm:grid-cols-2 mt-5">{[["Tuition / year",8000],["Accommodation / year",3000],["Food / year",2400],["Transport / year",1200]].map(([x,v]) => <label key={x} className="text-sm"><span className="font-medium">{x}</span><input type="number" defaultValue={v} className="mt-2 w-full rounded-lg border border-border bg-background px-3 py-2"/></label>)}</div><p className="mt-4 text-xs text-muted-foreground">Illustrative planning inputs. Use official fees when making a real decision.</p></div><div className="rounded-xl border border-border p-5"><h3 className="font-semibold">Funding capacity</h3><p className="text-sm text-muted-foreground mt-1">Model a family contribution and identify the remaining gap.</p><input type="range" min="0" max="5000" step="100" value={monthly} onChange={e => setMonthly(Number(e.target.value))} className="w-full mt-6"/><p className="text-xl font-semibold mt-2">GHS {monthly.toLocaleString()} / month</p><Link to="/scholarships" className="inline-flex items-center gap-2 mt-5 text-sm font-semibold">Find scholarship matches <ArrowRight className="h-4 w-4"/></Link></div></div>}

    {tab === "Skills" && <div className="mt-6 rounded-xl border border-border p-5"><div className="flex justify-between"><div><h3 className="font-semibold">Skills gap for {goal}</h3><p className="text-sm text-muted-foreground">Prioritize skills, then prove them through projects.</p></div><TrendingUp className="h-5 w-5 text-primary"/></div><div className="space-y-4 mt-6">{skills.map(([name,level,value]) => <div key={name}><div className="flex justify-between text-sm mb-2"><span className="font-medium">{name}</span><span className="text-muted-foreground">{level} · {value}%</span></div><div className="h-2 rounded-full bg-muted overflow-hidden"><div className="h-full rounded-full bg-primary" style={{width:`${value}%`}}/></div></div>)}</div></div>}

    {tab === "Projects" && <div className="mt-6 grid gap-4 md:grid-cols-3">{projects.map(([level,name,outcome,effort]) => <article key={name} className="rounded-xl border border-border p-5"><span className="text-xs font-semibold text-primary">{level}</span><h3 className="font-semibold mt-3">{name}</h3><p className="text-sm text-muted-foreground mt-2">{outcome}</p><p className="text-xs text-muted-foreground mt-4">Estimated effort: {effort}</p><button className="mt-5 w-full rounded-lg border border-border px-3 py-2 text-sm font-medium hover:bg-muted/30">Add to my path</button></article>)}</div>}

    {tab === "Opportunities" && <div className="mt-6 grid gap-4 md:grid-cols-2">{opportunities.map(([type,name,href]) => <Link key={name} to={href as "/internships"} className="rounded-xl border border-border p-5 hover:bg-muted/30"><div className="flex justify-between"><span className="text-xs font-semibold text-primary">{type}</span><Trophy className="h-4 w-4 text-muted-foreground"/></div><h3 className="font-semibold mt-4">{name}</h3><span className="inline-flex items-center gap-1 mt-4 text-sm font-medium">Explore <ArrowRight className="h-4 w-4"/></span></Link>)}</div>}

    <p className="mt-6 text-xs text-muted-foreground">GhanaPathFinder guidance is not an admission guarantee or official fee quote. Verify deadlines, requirements and costs with the relevant provider.</p>
  </section>;
}
