import { useMemo, useState } from "react";
import { Link } from "@/lib/router-compat";
import { useQuery } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const shell="min-h-dvh bg-background text-foreground";
const card="rounded-xl border border-border bg-card p-5";
const Layout=({title,kicker,children}:{title:string;kicker:string;children:React.ReactNode})=><div className={shell}><Navbar/><main className="mx-auto max-w-7xl px-4 pb-24 pt-20 sm:px-6 lg:px-8"><p className="text-sm font-semibold text-primary">{kicker}</p><h1 className="mt-1 text-3xl font-bold">{title}</h1>{children}</main><Footer/></div>;

export function UniversityDirectory(){const [q,setQ]=useState("");const {data=[],isLoading}=useQuery({queryKey:["universities-directory"],queryFn:async()=>{const {data,error}=await supabase.from("universities").select("id,name,short_name,location,region,slug,verified,source_url").order("name");if(error)throw error;return data??[];}});const rows=data.filter((u:any)=>(String(u.name??"")+" "+String(u.short_name??"")).toLowerCase().includes(q.toLowerCase()));return <Layout title="University Directory" kicker="EDUCATION"><p className="mt-2 max-w-2xl text-muted-foreground">Explore universities in the GhanaPathFinder catalogue and open a full institutional profile.</p><input className="mt-6 w-full max-w-xl rounded-lg border border-border bg-background px-3 py-3" placeholder="Search universities" value={q} onChange={e=>setQ(e.target.value)}/>{isLoading?<p className="mt-8 text-muted-foreground">Loading universities...</p>:<div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{rows.map((u:any)=><Link key={u.id} to={"/university/"+u.slug} className={card+" hover:border-primary"}><h2 className="font-semibold">{u.short_name||u.name}</h2><p className="mt-1 text-sm text-muted-foreground">{u.location||u.region||"Ghana"}</p><p className="mt-4 text-sm font-semibold text-primary">Open profile →</p></Link>)}</div>}</Layout>;}

const score=(job:any,c:any)=>{const hay=(String(job.title??"")+" "+String(job.description??"")+" "+String(job.company_name??"")).toLowerCase();const fields=[c.professional_title,...(c.skills||[]),...(c.preferred_industries||[])].filter(Boolean).map(String);const hits=fields.filter((v:string)=>hay.includes(v.toLowerCase())).length;return hits*20+Math.min(Number(c.years_experience||0),10);};

export function EmployeePortal(){const {data:jobs=[]}=useQuery({queryKey:["employee-active-jobs"],queryFn:async()=>{const {data,error}=await supabase.from("opportunities").select("*").eq("status","active").order("created_at",{ascending:false}).limit(50);if(error)throw error;return data??[];}});return <Layout title="Job Seeker Workspace" kicker="CAREER"><p className="mt-2 max-w-2xl text-muted-foreground">Build your professional profile, discover active opportunities, track applications and control recruiter visibility.</p><div className="mt-6 grid gap-4 md:grid-cols-2 lg:grid-cols-4"><Link to="/profile" className={card+" hover:border-primary"}><h2 className="font-semibold">Professional profile</h2><p className="mt-2 text-sm text-muted-foreground">Title, experience, LinkedIn, skills and recruiter visibility.</p></Link><Link to="/cv-builder" className={card+" hover:border-primary"}><h2 className="font-semibold">CV builder</h2></Link><Link to="/skills" className={card+" hover:border-primary"}><h2 className="font-semibold">Skills gap</h2></Link><Link to="/applications" className={card+" hover:border-primary"}><h2 className="font-semibold">Applications</h2></Link></div><section className="mt-8"><h2 className="text-xl font-semibold">Top 5 hiring opportunities</h2><p className="text-sm text-muted-foreground">Records currently marked active in GhanaPathFinder.</p><div className="mt-4 grid gap-4 md:grid-cols-2 lg:grid-cols-5">{jobs.slice(0,5).map((j:any)=><article key={j.id} className={card}><p className="text-xs uppercase text-primary">{j.type||j.opportunity_type||"Job"}</p><h3 className="mt-2 font-semibold">{j.title}</h3><p className="mt-1 text-sm text-muted-foreground">{j.company_name||"Employer"}</p>{(j.apply_url||j.application_url)&&<a className="mt-4 inline-block text-sm font-semibold text-primary" href={j.apply_url||j.application_url} target="_blank" rel="noreferrer">Apply / verify →</a>}</article>)}</div></section></Layout>;}

export function EmployerPortal(){const [jobId,setJobId]=useState("");const {data:jobs=[]}=useQuery({queryKey:["employer-jobs"],queryFn:async()=>{const {data,error}=await supabase.from("opportunities").select("*").eq("status","active").order("created_at",{ascending:false}).limit(50);if(error)throw error;return data??[];}});const {data:talent=[]}=useQuery({queryKey:["talent-directory"],queryFn:async()=>{const {data,error}=await supabase.from("talent_directory").select("user_id,full_name,professional_title,years_experience,linkedin_url,city,preferred_locations,preferred_industries,skills,bio").eq("discoverable",true).limit(200);if(error)throw error;return data??[];}});const job=jobs.find((j:any)=>String(j.id)===jobId);const matches=useMemo(()=>job?talent.map((c:any)=>({...c,score:score(job,c)})).sort((a:any,b:any)=>b.score-a.score).slice(0,5):[],[job,talent]);return <Layout title="Employer Hiring Workspace" kicker="HIRING"><p className="mt-2 max-w-2xl text-muted-foreground">Post roles, review active opportunities and discover candidates who explicitly opted into recruiter visibility.</p><section className={card+" mt-6"}><label className="text-sm font-medium">Select an active job</label><select value={jobId} onChange={e=>setJobId(e.target.value)} className="mt-2 w-full rounded-lg border border-border bg-background px-3 py-3"><option value="">Choose a job</option>{jobs.map((j:any)=><option key={j.id} value={j.id}>{j.title} · {j.company_name||"Employer"}</option>)}</select></section>{job&&<section className="mt-8"><h2 className="text-xl font-semibold">Top 5 candidate matches</h2><p className="text-sm text-muted-foreground">GhanaPathFinder Talent Match, based on declared profile data.</p><div className="mt-4 grid gap-4 lg:grid-cols-5">{matches.length?matches.map((c:any)=><article key={c.user_id} className={card}><h3 className="font-semibold">{c.full_name||"Candidate"}</h3><p className="mt-1 text-sm text-muted-foreground">{c.professional_title||"Professional"}{c.city?" · "+c.city:""}</p><p className="mt-2 text-xs text-muted-foreground">{Number(c.years_experience||0)} years experience · match score {c.score}</p><p className="mt-3 text-xs text-muted-foreground">{(c.skills||[]).slice(0,4).join(" · ")}</p>{c.linkedin_url&&<a href={c.linkedin_url} target="_blank" rel="noreferrer" className="mt-4 inline-block text-xs font-semibold text-primary">Candidate LinkedIn →</a>}</article>):<div className={card+" lg:col-span-5"}>No opted-in candidates are available for this role yet.</div>}</div></section>}</Layout>;}

export function StartupPortal(){const [q,setQ]=useState("");const {data=[]}=useQuery({queryKey:["african-startups"],queryFn:async()=>{const {data,error}=await supabase.from("african_startups").select("*").order("capital_usd",{ascending:false}).limit(500);if(error)throw error;return data??[];}});const rows=data.filter((s:any)=>(String(s.company_name??"")+" "+String(s.country??"")+" "+String(s.sector??"")).toLowerCase().includes(q.toLowerCase()));return <Layout title="Startup Founder Workspace" kicker="AFRICAN STARTUP INTELLIGENCE"><p className="mt-2 max-w-3xl text-muted-foreground">Company discovery, funding intelligence, accelerators, grants, talent and market research.</p><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Link to="/startup-directory" className={card+" hover:border-primary"}><h2 className="font-semibold">Startup directory</h2><p className="mt-2 text-sm text-muted-foreground">{data.length} source-backed records.</p></Link><Link to="/opportunities" className={card+" hover:border-primary"}><h2 className="font-semibold">Funding & grants</h2></Link><Link to="/employee-directory" className={card+" hover:border-primary"}><h2 className="font-semibold">Talent</h2></Link><Link to="/community" className={card+" hover:border-primary"}><h2 className="font-semibold">Founder community</h2></Link></div><section className={card+" mt-8"}><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-xl font-semibold">African startup intelligence</h2><p className="mt-1 text-sm text-muted-foreground">Publicly reported funding or valuation of at least US$1m. Public-data directory, not a completeness claim.</p></div><input className="w-full max-w-sm rounded-lg border border-border bg-background px-3 py-2" placeholder="Search company, country or sector" value={q} onChange={e=>setQ(e.target.value)}/></div><div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-border"><th className="py-3 pr-4">Company</th><th className="py-3 pr-4">Country</th><th className="py-3 pr-4">Sector</th><th className="py-3 pr-4">Stage</th><th className="py-3 pr-4">Reported capital</th><th className="py-3 pr-4">Source</th></tr></thead><tbody>{rows.map((s:any)=><tr key={s.id} className="border-b border-border/60"><td className="py-3 pr-4 font-medium">{s.company_name}</td><td className="py-3 pr-4">{s.country||"Africa"}</td><td className="py-3 pr-4">{s.sector||"Technology"}</td><td className="py-3 pr-4">{s.stage||"—"}</td><td className="py-3 pr-4">{"$"+Number(s.capital_usd||0).toLocaleString()}</td><td className="py-3 pr-4"><a className="text-primary font-semibold" href={s.source_url} target="_blank" rel="noreferrer">Source →</a></td></tr>)}</tbody></table></div></section></Layout>;}

export function StudentPortal(){const {data:universities=[]}=useQuery({queryKey:["student-portal-universities"],queryFn:async()=>{const {data}=await supabase.from("universities").select("id,name,short_name,slug,location").order("name").limit(8);return data??[];}});return <Layout title="Student Workspace" kicker="EDUCATION"><p className="mt-2 max-w-3xl text-muted-foreground">A dedicated education workspace for institutions, programmes, funding and career paths.</p><div className="mt-6 grid gap-4 md:grid-cols-3"><Link to="/universities" className={card+" hover:border-primary"}><h2 className="font-semibold">University directory</h2></Link><Link to="/programmes" className={card+" hover:border-primary"}><h2 className="font-semibold">Programme explorer</h2></Link><Link to="/admission-match" className={card+" hover:border-primary"}><h2 className="font-semibold">Admission Match</h2></Link><Link to="/scholarships" className={card+" hover:border-primary"}><h2 className="font-semibold">Scholarships</h2></Link><Link to="/compare" className={card+" hover:border-primary"}><h2 className="font-semibold">Compare institutions</h2></Link><Link to="/my-path" className={card+" hover:border-primary"}><h2 className="font-semibold">My Path</h2></Link></div><section className="mt-8"><h2 className="text-xl font-semibold">Featured institutions</h2><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{universities.map((u:any)=><Link key={u.id} to={"/university/"+u.slug} className={card+" hover:border-primary"}><h3 className="font-semibold">{u.short_name||u.name}</h3><p className="mt-1 text-sm text-muted-foreground">{u.location||"Ghana"}</p></Link>)}</div></section></Layout>;}
