import { motion } from "framer-motion";
import { Lightbulb, ExternalLink, MapPin, Flame } from "@/lib/icons";
import SectionHeader from "./SectionHeader";

interface FounderStory { founders: string; company: string; place: string; year: string; tag?: string; story: string; lesson: string; source?: string; sourceLabel?: string; founderPhoto?: string; logo?: string; }

const logo = (domain: string) => `https://www.google.com/s2/favicons?sz=128&domain=${domain}`;

const stories: FounderStory[] = [
  { founders: "Ham Serunjogi & Maijid Moujaled", company: "Chipper Cash", place: "Uganda / Pan-African", year: "2018", story: "The founders started Chipper after experiencing how expensive and difficult cross-border money movement could be for Africans. They built around a problem they understood deeply and grew it into a major fintech.", lesson: "Your own frustration can be market research. Start with a problem you understand deeply.", source: "https://www.chippercash.com/leadership-team-member/ham-serunjogi", sourceLabel: "chippercash.com", founderPhoto: "https://cdn.prod.website-files.com/63c81b0c3ad92959b9062d4b/63c81b0c3ad92998ba062d77_ham.png", logo: logo("chippercash.com") },
  { founders: "Olugbenga 'GB' Agboola", company: "Flutterwave", place: "Nigeria / Pan-African", year: "2016", story: "Agboola and a team of finance and technology veterans built payment infrastructure to make it easier for businesses to accept and move money across Africa.", lesson: "Infrastructure can become the foundation for thousands of other businesses.", source: "https://flutterwave.com/us/blog/keep-going", sourceLabel: "flutterwave.com", founderPhoto: "https://v12.flutterwave.com/wp-content/uploads/2020/06/Olugbenga-Agboola-the-New-Flutterwave-CEO-TechCabal-1.jpg", logo: logo("flutterwave.com") },
  { founders: "Drew Durbin & Lincoln Quirk", company: "Wave", place: "Senegal / Pan-African", year: "2018", story: "The co-founders first built Sendwave around expensive international transfers to Africa, then turned to domestic payments and affordability.", lesson: "A second company can grow from a deeper problem discovered while solving the first one.", source: "https://www.wave.com/en/about/", sourceLabel: "wave.com", founderPhoto: "https://www.wave.com/img/exec-team/drew-headshot_hu26e580986edb815a810b42dc2193d8ab_653879_400x400_resize_q75_box.b26520ddeabfae69be32b04f93792e0e74838aa20d1b6d6fd1b5828df4e801e6.jpg", logo: logo("wave.com") },
  { founders: "Jesse Moore & M-KOPA founding team", company: "M-KOPA", place: "Kenya / Pan-African", year: "2010", story: "M-KOPA combined digital micropayments with connected products so customers could access useful hardware without paying the full cost upfront.", lesson: "Hardware, software, data and distribution can combine into a powerful African business model.", source: "https://www.m-kopa.com/about", sourceLabel: "m-kopa.com", founderPhoto: "https://cdn.prod.website-files.com/66dcaf74c5e6c9bbd1890ab1/66e2e657e9c76c635ea5575d_Jesse%20Moore%20headshot.jpg", logo: logo("m-kopa.com") },
  { founders: "Jeremy Johnson, Iyinoluwa Aboyeji & founding team", company: "Andela", place: "Nigeria / Pan-African", year: "2014", story: "Andela began with a simple premise: brilliant people exist everywhere, but opportunity is not distributed equally. The team built a bridge between African technologists and global companies.", lesson: "Talent is infrastructure too. Build the bridge between ability and opportunity.", source: "https://www.andela.com/about", sourceLabel: "andela.com", logo: logo("andela.com") },
  { founders: "Shola Akinlade & Ezra Olubi", company: "Paystack", place: "Nigeria", year: "2015", story: "Two Nigerian developers built payment infrastructure after seeing local businesses struggle to accept payments online. They focused on making the difficult plumbing easier for businesses to integrate.", lesson: "The unglamorous infrastructure underneath a market can be one of its biggest opportunities.", source: "https://paystack.com/gh/about", sourceLabel: "paystack.com", logo: logo("paystack.com") },
  { founders: "Bright Simons", company: "mPedigree", place: "Ghana", year: "2007", story: "Simons recognised a traceability problem in counterfeit medicine and built verification technology around tools people already knew how to use.", lesson: "The best technology is sometimes the technology your users already know.", source: "https://mpedigree.com/", sourceLabel: "mpedigree.com", founderPhoto: "https://commons.wikimedia.org/wiki/Special:Redirect/file/Bright%20Simons%20-%20TED%20Fellows%20Talk.jpg", logo: logo("mpedigree.com") },
  { founders: "Patrick Awuah", company: "Ashesi University", place: "Ghana", year: "2002", story: "Awuah returned to Ghana to build an institution focused on ethical, entrepreneurial leadership. Ashesi started with a pioneering class of 30 students and grew through proof and persistence.", lesson: "A serious institution can begin with a small first cohort. Scale can come after proof.", source: "https://ashesi.edu.gh/about/", sourceLabel: "ashesi.edu.gh", founderPhoto: "https://commons.wikimedia.org/wiki/Special:Redirect/file/Patrick%20Awuah%20(Ashesi).jpg", logo: logo("ashesi.edu.gh") },
  { founders: "Alloysius Attah & Emmanuel O. Addai", company: "Farmerline", place: "Ghana / Pan-African", year: "2013", tag: "Ghana", story: "Farmerline started with a simple idea: use technology to give farmers better access to information, inputs, finance and markets. It grew from a small Ghanaian startup into a major agricultural technology company.", lesson: "Solve a basic problem close to home, then build the systems that let the solution travel.", source: "https://farmerline.co/our-story/", sourceLabel: "farmerline.co", logo: logo("farmerline.co") },
  { founders: "Alex Bram, Ernest Apenteng & Leslie Gyimah", company: "Hubtel", place: "Ghana", year: "2005", tag: "Ghana", story: "Hubtel began as SMSGH, helping Ghanaian businesses communicate with customers. The company expanded from messaging into payments and commerce while keeping the customer problem at the centre.", lesson: "A product can evolve dramatically when you keep following the real customer need.", source: "https://news.hubtel.com/smsgh-rebranded-hubtel/", sourceLabel: "hubtel.com", logo: logo("hubtel.com") },
  { founders: "Gregory Rockson & mPharma founding team", company: "mPharma", place: "Ghana / Pan-African", year: "2013", tag: "Ghana", story: "mPharma was built around a difficult healthcare supply-chain problem: pharmacies and patients often struggle with reliable access to medicines. The company developed technology and operating systems around that gap.", lesson: "Large opportunities often sit inside broken systems that people have learned to tolerate.", source: "https://mpharma.com/our-vision/", sourceLabel: "mpharma.com", logo: logo("mpharma.com") },
  { founders: "Alex Bram, Ernest Apenteng & Leslie Gyimah", company: "SMSGH → Hubtel", place: "Ghana", year: "2005", tag: "Origin", story: "Before Hubtel became the broader payments and commerce platform it is today, SMSGH focused on business messaging. The evolution shows how a Ghanaian technology company can expand from one narrow wedge into a larger infrastructure platform.", lesson: "Start narrow enough to win, then expand when customers pull you forward.", source: "https://news.hubtel.com/smsgh-rebranded-hubtel/", sourceLabel: "hubtel.com", logo: logo("hubtel.com") },
  { founders: "Nathan Nwachuku & Maxwell Maduka", company: "Terra Industries", place: "Nigeria / Ghana expansion", year: "2026 watch", tag: "Rising", story: "Terra became one of the most closely watched African deep-tech companies in 2026. Its founder story is useful as a business case study in ambitious technical infrastructure, manufacturing and capital-intensive execution.", lesson: "Ambitious technical companies still need a painful problem, strong execution, customers and disciplined capital use." },
];

const StartupStories = () => (
  <section id="founders" className="py-12 lg:py-28 px-4">
    <div className="max-w-7xl mx-auto">
      <SectionHeader badge="African founders" title="See how real companies" highlight="actually get built" description="Stories from African founders, with a strong focus on Ghanaian companies and founders building from Ghana." />
      <div className="flex items-center gap-2 text-xs text-muted-foreground mb-5"><Flame className="h-3.5 w-3.5 text-primary" /><span>Rising tags reflect current ecosystem coverage, not a promise of future success.</span></div>
      <div className="flex hscroll hscroll-bleed snap-x snap-mandatory scroll-smooth [&>*]:w-[19rem] [&>*]:shrink-0 [&>*]:snap-start md:grid md:grid-cols-2 lg:grid-cols-3 md:overflow-visible md:mx-0 md:px-0 md:[&>*]:w-auto gap-5">
        {stories.map((s, i) => (
          <motion.article key={`${s.company}-${i}`} initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: (i % 3) * 0.06, duration: 0.35 }} className="bg-glass rounded-xl overflow-hidden card-hover group flex flex-col">
            {s.founderPhoto ? <div className="relative h-44 bg-muted overflow-hidden"><img src={s.founderPhoto} alt={`${s.founders} of ${s.company}`} loading="lazy" className="w-full h-full object-cover object-center transition-transform duration-500 group-hover:scale-[1.02]" referrerPolicy="no-referrer" /><div className="absolute inset-x-0 bottom-0 h-20 bg-gradient-to-t from-black/60 to-transparent" /><div className="absolute left-4 bottom-4 flex items-center gap-2">{s.logo && <div className="w-9 h-9 rounded-lg bg-white p-1.5 shadow-sm flex items-center justify-center"><img src={s.logo} alt={`${s.company} logo`} loading="lazy" className="w-full h-full object-contain" onError={(e) => { e.currentTarget.style.display = "none"; }} /></div>}<span className="text-xs font-medium text-white bg-black/35 backdrop-blur-sm rounded-full px-2.5 py-1">{s.year}</span></div></div> : <div className="h-44 bg-gradient-to-br from-primary/15 via-background to-secondary flex items-end justify-between p-5"><div className="w-12 h-12 rounded-xl bg-white p-2 shadow-sm flex items-center justify-center"><img src={s.logo} alt={`${s.company} logo`} loading="lazy" className="w-full h-full object-contain" onError={(e) => { e.currentTarget.style.display = "none"; }} /></div><span className="text-sm font-semibold text-foreground">{s.year}</span></div>}
            <div className="p-5 flex flex-col flex-1"><div className="flex items-center justify-between gap-2"><h3 className="font-display font-semibold text-foreground text-lg leading-tight">{s.company}</h3>{s.tag && <span className="text-[10px] uppercase tracking-wider font-semibold text-primary">{s.tag}</span>}</div><p className="text-sm text-foreground/70 mt-1">{s.founders}</p><div className="flex items-center gap-1 text-xs text-muted-foreground mt-2 mb-3"><MapPin className="h-3 w-3 shrink-0" />{s.place}</div><p className="text-sm text-muted-foreground leading-relaxed">{s.story}</p><div className="pt-4 mt-auto"><div className="flex items-start gap-2 pt-3 border-t border-border/50"><Lightbulb className="h-3.5 w-3.5 text-primary mt-0.5 shrink-0" /><p className="text-xs text-primary/80 italic">{s.lesson}</p></div>{s.source && <a href={s.source} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1.5 text-xs text-muted-foreground hover:text-primary transition-colors mt-3"><ExternalLink className="h-3 w-3" /> Source: {s.sourceLabel}</a>}</div></div>
          </motion.article>
        ))}
      </div>
    </div>
  </section>
);

export default StartupStories;
