/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdmissionMatchRouteImport } from './routes/admission-match'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CompareScholarshipsRouteImport } from './routes/compare-scholarships'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as InspirationRouteImport } from './routes/inspiration'
import { Route as MatcherRouteImport } from './routes/matcher'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as PreferencesRouteImport } from './routes/preferences'
import { Route as ProgrammesRouteImport } from './routes/programmes'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as ScholarshipsRouteImport } from './routes/scholarships'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AdminDataRouteImport } from './routes/admin/data'
import { Route as ProgrammeSlugRouteImport } from './routes/programme/$slug'
import { Route as UniversitySlugRouteImport } from './routes/university/$slug'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionMatchRoute = AdmissionMatchRouteImport.update({
  id: '/admission-match',
  path: '/admission-match',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareScholarshipsRoute = CompareScholarshipsRouteImport.update({
  id: '/compare-scholarships',
  path: '/compare-scholarships',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InspirationRoute = InspirationRouteImport.update({
  id: '/inspiration',
  path: '/inspiration',
  getParentRoute: () => rootRouteImport,
} as any)
const MatcherRoute = MatcherRouteImport.update({
  id: '/matcher',
  path: '/matcher',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesRoute = PreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesRoute = ProgrammesRouteImport.update({
  id: '/programmes',
  path: '/programmes',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ScholarshipsRoute = ScholarshipsRouteImport.update({
  id: '/scholarships',
  path: '/scholarships',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDataRoute = AdminDataRouteImport.update({
  id: '/admin/data',
  path: '/admin/data',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammeSlugRoute = ProgrammeSlugRouteImport.update({
  id: '/programme/$slug',
  path: '/programme/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversitySlugRoute = UniversitySlugRouteImport.update({
  id: '/university/$slug',
  path: '/university/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admission-match': typeof AdmissionMatchRoute
  '/applications': typeof ApplicationsRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/compare-scholarships': typeof CompareScholarshipsRoute
  '/dashboard': typeof DashboardRoute
  '/inspiration': typeof InspirationRoute
  '/matcher': typeof MatcherRoute
  '/onboarding': typeof OnboardingRoute
  '/parent': typeof ParentRoute
  '/preferences': typeof PreferencesRoute
  '/programmes': typeof ProgrammesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saved': typeof SavedRoute
  '/scholarships': typeof ScholarshipsRoute
  '/search': typeof SearchRoute
  '/admin/data': typeof AdminDataRoute
  '/programme/$slug': typeof ProgrammeSlugRoute
  '/university/$slug': typeof UniversitySlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admission-match': typeof AdmissionMatchRoute
  '/applications': typeof ApplicationsRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/compare-scholarships': typeof CompareScholarshipsRoute
  '/dashboard': typeof DashboardRoute
  '/inspiration': typeof InspirationRoute
  '/matcher': typeof MatcherRoute
  '/onboarding': typeof OnboardingRoute
  '/parent': typeof ParentRoute
  '/preferences': typeof PreferencesRoute
  '/programmes': typeof ProgrammesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saved': typeof SavedRoute
  '/scholarships': typeof ScholarshipsRoute
  '/search': typeof SearchRoute
  '/admin/data': typeof AdminDataRoute
  '/programme/$slug': typeof ProgrammeSlugRoute
  '/university/$slug': typeof UniversitySlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admission-match': typeof AdmissionMatchRoute
  '/applications': typeof ApplicationsRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/compare-scholarships': typeof CompareScholarshipsRoute
  '/dashboard': typeof DashboardRoute
  '/inspiration': typeof InspirationRoute
  '/matcher': typeof MatcherRoute
  '/onboarding': typeof OnboardingRoute
  '/parent': typeof ParentRoute
  '/preferences': typeof PreferencesRoute
  '/programmes': typeof ProgrammesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saved': typeof SavedRoute
  '/scholarships': typeof ScholarshipsRoute
  '/search': typeof SearchRoute
  '/admin/data': typeof AdminDataRoute
  '/programme/$slug': typeof ProgrammeSlugRoute
  '/university/$slug': typeof UniversitySlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admission-match'
    | '/applications'
    | '/auth'
    | '/compare'
    | '/compare-scholarships'
    | '/dashboard'
    | '/inspiration'
    | '/matcher'
    | '/onboarding'
    | '/parent'
    | '/preferences'
    | '/programmes'
    | '/reset-password'
    | '/saved'
    | '/scholarships'
    | '/search'
    | '/admin/data'
    | '/programme/$slug'
    | '/university/$slug'
    | '/.lovable/oauth/consent'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admission-match'
    | '/applications'
    | '/auth'
    | '/compare'
    | '/compare-scholarships'
    | '/dashboard'
    | '/inspiration'
    | '/matcher'
    | '/onboarding'
    | '/parent'
    | '/preferences'
    | '/programmes'
    | '/reset-password'
    | '/saved'
    | '/scholarships'
    | '/search'
    | '/admin/data'
    | '/programme/$slug'
    | '/university/$slug'
    | '/.lovable/oauth/consent'
  id:
    | '__root__'
    | '/'
    | '/admission-match'
    | '/applications'
    | '/auth'
    | '/compare'
    | '/compare-scholarships'
    | '/dashboard'
    | '/inspiration'
    | '/matcher'
    | '/onboarding'
    | '/parent'
    | '/preferences'
    | '/programmes'
    | '/reset-password'
    | '/saved'
    | '/scholarships'
    | '/search'
    | '/admin/data'
    | '/programme/$slug'
    | '/university/$slug'
    | '/.lovable/oauth/consent'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdmissionMatchRoute: typeof AdmissionMatchRoute
  ApplicationsRoute: typeof ApplicationsRoute
  AuthRoute: typeof AuthRoute
  CompareRoute: typeof CompareRoute
  CompareScholarshipsRoute: typeof CompareScholarshipsRoute
  DashboardRoute: typeof DashboardRoute
  InspirationRoute: typeof InspirationRoute
  MatcherRoute: typeof MatcherRoute
  OnboardingRoute: typeof OnboardingRoute
  ParentRoute: typeof ParentRoute
  PreferencesRoute: typeof PreferencesRoute
  ProgrammesRoute: typeof ProgrammesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SavedRoute: typeof SavedRoute
  ScholarshipsRoute: typeof ScholarshipsRoute
  SearchRoute: typeof SearchRoute
  AdminDataRoute: typeof AdminDataRoute
  ProgrammeSlugRoute: typeof ProgrammeSlugRoute
  UniversitySlugRoute: typeof UniversitySlugRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admission-match': {
      id: '/admission-match'
      path: '/admission-match'
      fullPath: '/admission-match'
      preLoaderRoute: typeof AdmissionMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare-scholarships': {
      id: '/compare-scholarships'
      path: '/compare-scholarships'
      fullPath: '/compare-scholarships'
      preLoaderRoute: typeof CompareScholarshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspiration': {
      id: '/inspiration'
      path: '/inspiration'
      fullPath: '/inspiration'
      preLoaderRoute: typeof InspirationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matcher': {
      id: '/matcher'
      path: '/matcher'
      fullPath: '/matcher'
      preLoaderRoute: typeof MatcherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferences': {
      id: '/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof PreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes': {
      id: '/programmes'
      path: '/programmes'
      fullPath: '/programmes'
      preLoaderRoute: typeof ProgrammesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarships': {
      id: '/scholarships'
      path: '/scholarships'
      fullPath: '/scholarships'
      preLoaderRoute: typeof ScholarshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/data': {
      id: '/admin/data'
      path: '/admin/data'
      fullPath: '/admin/data'
      preLoaderRoute: typeof AdminDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programme/$slug': {
      id: '/programme/$slug'
      path: '/programme/$slug'
      fullPath: '/programme/$slug'
      preLoaderRoute: typeof ProgrammeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/university/$slug': {
      id: '/university/$slug'
      path: '/university/$slug'
      fullPath: '/university/$slug'
      preLoaderRoute: typeof UniversitySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdmissionMatchRoute: AdmissionMatchRoute,
  ApplicationsRoute: ApplicationsRoute,
  AuthRoute: AuthRoute,
  CompareRoute: CompareRoute,
  CompareScholarshipsRoute: CompareScholarshipsRoute,
  DashboardRoute: DashboardRoute,
  InspirationRoute: InspirationRoute,
  MatcherRoute: MatcherRoute,
  OnboardingRoute: OnboardingRoute,
  ParentRoute: ParentRoute,
  PreferencesRoute: PreferencesRoute,
  ProgrammesRoute: ProgrammesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SavedRoute: SavedRoute,
  ScholarshipsRoute: ScholarshipsRoute,
  SearchRoute: SearchRoute,
  AdminDataRoute: AdminDataRoute,
  ProgrammeSlugRoute: ProgrammeSlugRoute,
  UniversitySlugRoute: UniversitySlugRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
