/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdmissionMatchRouteImport } from './routes/admission-match'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CompareScholarshipsRouteImport } from './routes/compare-scholarships'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as InspirationRouteImport } from './routes/inspiration'
import { Route as MatcherRouteImport } from './routes/matcher'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as PreferencesRouteImport } from './routes/preferences'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfessionalCouncilsRouteImport } from './routes/professional-councils'
import { Route as ReferencesRouteImport } from './routes/references'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SearchRouteImport } from './routes/search'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminDataRouteImport } from './routes/admin/data'
import { Route as CareersIndexRouteImport } from './routes/careers/index'
import { Route as CareersSlugRouteImport } from './routes/careers/$slug'
import { Route as ProgrammeSlugRouteImport } from './routes/programme/$slug'
import { Route as ProgrammesIndexRouteImport } from './routes/programmes/index'
import { Route as ProgrammesSlugRouteImport } from './routes/programmes/$slug'
import { Route as ScholarshipsIndexRouteImport } from './routes/scholarships/index'
import { Route as ScholarshipsSlugRouteImport } from './routes/scholarships/$slug'
import { Route as UniversitiesSlugRouteImport } from './routes/universities/$slug'
import { Route as UniversitySlugRouteImport } from './routes/university/$slug'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as FunctionsV1McpRouteImport } from './routes/functions/v1/mcp'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionMatchRoute = AdmissionMatchRouteImport.update({
  id: '/admission-match',
  path: '/admission-match',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareScholarshipsRoute = CompareScholarshipsRouteImport.update({
  id: '/compare-scholarships',
  path: '/compare-scholarships',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const InspirationRoute = InspirationRouteImport.update({
  id: '/inspiration',
  path: '/inspiration',
  getParentRoute: () => rootRouteImport,
} as any)
const MatcherRoute = MatcherRouteImport.update({
  id: '/matcher',
  path: '/matcher',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesRoute = PreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionalCouncilsRoute = ProfessionalCouncilsRouteImport.update({
  id: '/professional-councils',
  path: '/professional-councils',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferencesRoute = ReferencesRouteImport.update({
  id: '/references',
  path: '/references',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDataRoute = AdminDataRouteImport.update({
  id: '/admin/data',
  path: '/admin/data',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersIndexRoute = CareersIndexRouteImport.update({
  id: '/careers/',
  path: '/careers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersSlugRoute = CareersSlugRouteImport.update({
  id: '/careers/$slug',
  path: '/careers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammeSlugRoute = ProgrammeSlugRouteImport.update({
  id: '/programme/$slug',
  path: '/programme/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesIndexRoute = ProgrammesIndexRouteImport.update({
  id: '/programmes/',
  path: '/programmes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesSlugRoute = ProgrammesSlugRouteImport.update({
  id: '/programmes/$slug',
  path: '/programmes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ScholarshipsIndexRoute = ScholarshipsIndexRouteImport.update({
  id: '/scholarships/',
  path: '/scholarships/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScholarshipsSlugRoute = ScholarshipsSlugRouteImport.update({
  id: '/scholarships/$slug',
  path: '/scholarships/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversitiesSlugRoute = UniversitiesSlugRouteImport.update({
  id: '/universities/$slug',
  path: '/universities/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversitySlugRoute = UniversitySlugRouteImport.update({
  id: '/university/$slug',
  path: '/university/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const FunctionsV1McpRoute = FunctionsV1McpRouteImport.update({
  id: '/functions/v1/mcp',
  path: '/functions/v1/mcp',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admission-match': typeof AdmissionMatchRoute
  '/applications': typeof ApplicationsRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/compare': typeof CompareRoute
  '/compare-scholarships': typeof CompareScholarshipsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/disclaimer': typeof DisclaimerRoute
  '/inspiration': typeof InspirationRoute
  '/matcher': typeof MatcherRoute
  '/onboarding': typeof OnboardingRoute
  '/parent': typeof ParentRoute
  '/preferences': typeof PreferencesRoute
  '/privacy': typeof PrivacyRoute
  '/professional-councils': typeof ProfessionalCouncilsRoute
  '/references': typeof ReferencesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/data': typeof AdminDataRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/programme/$slug': typeof ProgrammeSlugRoute
  '/programmes/$slug': typeof ProgrammesSlugRoute
  '/scholarships/$slug': typeof ScholarshipsSlugRoute
  '/universities/$slug': typeof UniversitiesSlugRoute
  '/university/$slug': typeof UniversitySlugRoute
  '/careers/': typeof CareersIndexRoute
  '/programmes/': typeof ProgrammesIndexRoute
  '/scholarships/': typeof ScholarshipsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/functions/v1/mcp': typeof FunctionsV1McpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admission-match': typeof AdmissionMatchRoute
  '/applications': typeof ApplicationsRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/compare': typeof CompareRoute
  '/compare-scholarships': typeof CompareScholarshipsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/disclaimer': typeof DisclaimerRoute
  '/inspiration': typeof InspirationRoute
  '/matcher': typeof MatcherRoute
  '/onboarding': typeof OnboardingRoute
  '/parent': typeof ParentRoute
  '/preferences': typeof PreferencesRoute
  '/privacy': typeof PrivacyRoute
  '/professional-councils': typeof ProfessionalCouncilsRoute
  '/references': typeof ReferencesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/data': typeof AdminDataRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/programme/$slug': typeof ProgrammeSlugRoute
  '/programmes/$slug': typeof ProgrammesSlugRoute
  '/scholarships/$slug': typeof ScholarshipsSlugRoute
  '/universities/$slug': typeof UniversitiesSlugRoute
  '/university/$slug': typeof UniversitySlugRoute
  '/careers': typeof CareersIndexRoute
  '/programmes': typeof ProgrammesIndexRoute
  '/scholarships': typeof ScholarshipsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/functions/v1/mcp': typeof FunctionsV1McpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admission-match': typeof AdmissionMatchRoute
  '/applications': typeof ApplicationsRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/compare': typeof CompareRoute
  '/compare-scholarships': typeof CompareScholarshipsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/disclaimer': typeof DisclaimerRoute
  '/inspiration': typeof InspirationRoute
  '/matcher': typeof MatcherRoute
  '/onboarding': typeof OnboardingRoute
  '/parent': typeof ParentRoute
  '/preferences': typeof PreferencesRoute
  '/privacy': typeof PrivacyRoute
  '/professional-councils': typeof ProfessionalCouncilsRoute
  '/references': typeof ReferencesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/data': typeof AdminDataRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/programme/$slug': typeof ProgrammeSlugRoute
  '/programmes/$slug': typeof ProgrammesSlugRoute
  '/scholarships/$slug': typeof ScholarshipsSlugRoute
  '/universities/$slug': typeof UniversitiesSlugRoute
  '/university/$slug': typeof UniversitySlugRoute
  '/careers/': typeof CareersIndexRoute
  '/programmes/': typeof ProgrammesIndexRoute
  '/scholarships/': typeof ScholarshipsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/functions/v1/mcp': typeof FunctionsV1McpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admission-match'
    | '/applications'
    | '/auth'
    | '/community'
    | '/compare'
    | '/compare-scholarships'
    | '/contact'
    | '/dashboard'
    | '/disclaimer'
    | '/inspiration'
    | '/matcher'
    | '/onboarding'
    | '/parent'
    | '/preferences'
    | '/privacy'
    | '/professional-councils'
    | '/references'
    | '/reset-password'
    | '/saved'
    | '/search'
    | '/terms'
    | '/admin/analytics'
    | '/admin/data'
    | '/careers/$slug'
    | '/programme/$slug'
    | '/programmes/$slug'
    | '/scholarships/$slug'
    | '/universities/$slug'
    | '/university/$slug'
    | '/careers/'
    | '/programmes/'
    | '/scholarships/'
    | '/.lovable/oauth/consent'
    | '/functions/v1/mcp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admission-match'
    | '/applications'
    | '/auth'
    | '/community'
    | '/compare'
    | '/compare-scholarships'
    | '/contact'
    | '/dashboard'
    | '/disclaimer'
    | '/inspiration'
    | '/matcher'
    | '/onboarding'
    | '/parent'
    | '/preferences'
    | '/privacy'
    | '/professional-councils'
    | '/references'
    | '/reset-password'
    | '/saved'
    | '/search'
    | '/terms'
    | '/admin/analytics'
    | '/admin/data'
    | '/careers/$slug'
    | '/programme/$slug'
    | '/programmes/$slug'
    | '/scholarships/$slug'
    | '/universities/$slug'
    | '/university/$slug'
    | '/careers'
    | '/programmes'
    | '/scholarships'
    | '/.lovable/oauth/consent'
    | '/functions/v1/mcp'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admission-match'
    | '/applications'
    | '/auth'
    | '/community'
    | '/compare'
    | '/compare-scholarships'
    | '/contact'
    | '/dashboard'
    | '/disclaimer'
    | '/inspiration'
    | '/matcher'
    | '/onboarding'
    | '/parent'
    | '/preferences'
    | '/privacy'
    | '/professional-councils'
    | '/references'
    | '/reset-password'
    | '/saved'
    | '/search'
    | '/terms'
    | '/admin/analytics'
    | '/admin/data'
    | '/careers/$slug'
    | '/programme/$slug'
    | '/programmes/$slug'
    | '/scholarships/$slug'
    | '/universities/$slug'
    | '/university/$slug'
    | '/careers/'
    | '/programmes/'
    | '/scholarships/'
    | '/.lovable/oauth/consent'
    | '/functions/v1/mcp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdmissionMatchRoute: typeof AdmissionMatchRoute
  ApplicationsRoute: typeof ApplicationsRoute
  AuthRoute: typeof AuthRoute
  CommunityRoute: typeof CommunityRoute
  CompareRoute: typeof CompareRoute
  CompareScholarshipsRoute: typeof CompareScholarshipsRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  DisclaimerRoute: typeof DisclaimerRoute
  InspirationRoute: typeof InspirationRoute
  MatcherRoute: typeof MatcherRoute
  OnboardingRoute: typeof OnboardingRoute
  ParentRoute: typeof ParentRoute
  PreferencesRoute: typeof PreferencesRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfessionalCouncilsRoute: typeof ProfessionalCouncilsRoute
  ReferencesRoute: typeof ReferencesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SavedRoute: typeof SavedRoute
  SearchRoute: typeof SearchRoute
  TermsRoute: typeof TermsRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminDataRoute: typeof AdminDataRoute
  CareersSlugRoute: typeof CareersSlugRoute
  ProgrammeSlugRoute: typeof ProgrammeSlugRoute
  ProgrammesSlugRoute: typeof ProgrammesSlugRoute
  ScholarshipsSlugRoute: typeof ScholarshipsSlugRoute
  UniversitiesSlugRoute: typeof UniversitiesSlugRoute
  UniversitySlugRoute: typeof UniversitySlugRoute
  CareersIndexRoute: typeof CareersIndexRoute
  ProgrammesIndexRoute: typeof ProgrammesIndexRoute
  ScholarshipsIndexRoute: typeof ScholarshipsIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  FunctionsV1McpRoute: typeof FunctionsV1McpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admission-match': {
      id: '/admission-match'
      path: '/admission-match'
      fullPath: '/admission-match'
      preLoaderRoute: typeof AdmissionMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare-scholarships': {
      id: '/compare-scholarships'
      path: '/compare-scholarships'
      fullPath: '/compare-scholarships'
      preLoaderRoute: typeof CompareScholarshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspiration': {
      id: '/inspiration'
      path: '/inspiration'
      fullPath: '/inspiration'
      preLoaderRoute: typeof InspirationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matcher': {
      id: '/matcher'
      path: '/matcher'
      fullPath: '/matcher'
      preLoaderRoute: typeof MatcherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferences': {
      id: '/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof PreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professional-councils': {
      id: '/professional-councils'
      path: '/professional-councils'
      fullPath: '/professional-councils'
      preLoaderRoute: typeof ProfessionalCouncilsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/references': {
      id: '/references'
      path: '/references'
      fullPath: '/references'
      preLoaderRoute: typeof ReferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/data': {
      id: '/admin/data'
      path: '/admin/data'
      fullPath: '/admin/data'
      preLoaderRoute: typeof AdminDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/': {
      id: '/careers/'
      path: '/careers'
      fullPath: '/careers/'
      preLoaderRoute: typeof CareersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/$slug': {
      id: '/careers/$slug'
      path: '/careers/$slug'
      fullPath: '/careers/$slug'
      preLoaderRoute: typeof CareersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programme/$slug': {
      id: '/programme/$slug'
      path: '/programme/$slug'
      fullPath: '/programme/$slug'
      preLoaderRoute: typeof ProgrammeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/': {
      id: '/programmes/'
      path: '/programmes'
      fullPath: '/programmes/'
      preLoaderRoute: typeof ProgrammesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/$slug': {
      id: '/programmes/$slug'
      path: '/programmes/$slug'
      fullPath: '/programmes/$slug'
      preLoaderRoute: typeof ProgrammesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarships/': {
      id: '/scholarships/'
      path: '/scholarships'
      fullPath: '/scholarships/'
      preLoaderRoute: typeof ScholarshipsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarships/$slug': {
      id: '/scholarships/$slug'
      path: '/scholarships/$slug'
      fullPath: '/scholarships/$slug'
      preLoaderRoute: typeof ScholarshipsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/universities/$slug': {
      id: '/universities/$slug'
      path: '/universities/$slug'
      fullPath: '/universities/$slug'
      preLoaderRoute: typeof UniversitiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/university/$slug': {
      id: '/university/$slug'
      path: '/university/$slug'
      fullPath: '/university/$slug'
      preLoaderRoute: typeof UniversitySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/functions/v1/mcp': {
      id: '/functions/v1/mcp'
      path: '/functions/v1/mcp'
      fullPath: '/functions/v1/mcp'
      preLoaderRoute: typeof FunctionsV1McpRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdmissionMatchRoute: AdmissionMatchRoute,
  ApplicationsRoute: ApplicationsRoute,
  AuthRoute: AuthRoute,
  CommunityRoute: CommunityRoute,
  CompareRoute: CompareRoute,
  CompareScholarshipsRoute: CompareScholarshipsRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  DisclaimerRoute: DisclaimerRoute,
  InspirationRoute: InspirationRoute,
  MatcherRoute: MatcherRoute,
  OnboardingRoute: OnboardingRoute,
  ParentRoute: ParentRoute,
  PreferencesRoute: PreferencesRoute,
  PrivacyRoute: PrivacyRoute,
  ProfessionalCouncilsRoute: ProfessionalCouncilsRoute,
  ReferencesRoute: ReferencesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SavedRoute: SavedRoute,
  SearchRoute: SearchRoute,
  TermsRoute: TermsRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminDataRoute: AdminDataRoute,
  CareersSlugRoute: CareersSlugRoute,
  ProgrammeSlugRoute: ProgrammeSlugRoute,
  ProgrammesSlugRoute: ProgrammesSlugRoute,
  ScholarshipsSlugRoute: ScholarshipsSlugRoute,
  UniversitiesSlugRoute: UniversitiesSlugRoute,
  UniversitySlugRoute: UniversitySlugRoute,
  CareersIndexRoute: CareersIndexRoute,
  ProgrammesIndexRoute: ProgrammesIndexRoute,
  ScholarshipsIndexRoute: ScholarshipsIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  FunctionsV1McpRoute: FunctionsV1McpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
