// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/get-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.7";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys["default"], ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/get-profile.ts
var get_profile_default = defineTool({
  name: "get_profile",
  title: "Get my GhanaPath profile",
  description: "Fetch the signed-in student's GhanaPath profile, WASSCE results and match preferences.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const [profile, wassce, prefs] = await Promise.all([
      supabase.from("profiles").select("*").eq("id", userId).maybeSingle(),
      supabase.from("wassce_results").select("subject, grade").eq("user_id", userId),
      supabase.from("match_preferences").select("*").eq("user_id", userId).maybeSingle()
    ]);
    const error = profile.error ?? wassce.error ?? prefs.error;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const payload = {
      profile: profile.data,
      wassceResults: wassce.data ?? [],
      matchPreferences: prefs.data
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-saved-items.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.24.2";
var list_saved_items_default = defineTool2({
  name: "list_saved_items",
  title: "List saved universities and scholarships",
  description: "List the signed-in student's saved GhanaPath items (universities, programmes, scholarships, careers).",
  inputSchema: {
    itemType: z.string().trim().min(1).optional().describe("Optional filter, e.g. 'scholarship' or 'university'."),
    limit: z.number().int().min(1).max(100).default(50).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ itemType, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("saved_items").select("id, item_type, item_key, title, subtitle, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 50);
    if (itemType) query = query.eq("item_type", itemType);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-applications.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.24.2";
var list_applications_default = defineTool3({
  name: "list_scholarship_applications",
  title: "List scholarship applications",
  description: "List the signed-in student's tracked scholarship applications with status, deadline and notes.",
  inputSchema: {
    status: z2.string().trim().min(1).optional().describe("Optional status filter, e.g. interested, preparing, submitted, interview, awarded, rejected.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("scholarship_applications").select("id, scholarship_name, provider, status, deadline, link, notes, submitted_at").eq("user_id", ctx.getUserId()).order("deadline", { ascending: true, nullsFirst: false });
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { applications: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/track-application.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.24.2";
var STATUSES = ["interested", "preparing", "submitted", "interview", "awarded", "rejected"];
var track_application_default = defineTool4({
  name: "track_scholarship_application",
  title: "Add or update a scholarship application",
  description: "Add a scholarship to the signed-in student's tracker, or update the status/deadline/notes of an existing one.",
  inputSchema: {
    scholarshipName: z3.string().trim().min(1).describe("Scholarship name."),
    status: z3.enum(STATUSES).default("interested").optional(),
    provider: z3.string().trim().min(1).optional(),
    deadline: z3.string().trim().min(1).optional().describe("Deadline as YYYY-MM-DD."),
    link: z3.string().trim().url().optional(),
    notes: z3.string().trim().max(2e3).optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ scholarshipName, status, provider, deadline, link, notes }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const { data: existing, error: findError } = await supabase.from("scholarship_applications").select("id").eq("user_id", userId).eq("scholarship_name", scholarshipName).maybeSingle();
    if (findError) return { content: [{ type: "text", text: findError.message }], isError: true };
    const patch = {};
    if (status) patch["status"] = status;
    if (provider) patch["provider"] = provider;
    if (deadline) patch["deadline"] = deadline;
    if (link) patch["link"] = link;
    if (notes) patch["notes"] = notes;
    if (status === "submitted") patch["submitted_at"] = (/* @__PURE__ */ new Date()).toISOString();
    const { data, error } = existing ? await supabase.from("scholarship_applications").update(patch).eq("id", existing.id).eq("user_id", userId).select() : await supabase.from("scholarship_applications").insert({
      user_id: userId,
      scholarship_name: scholarshipName,
      status: status ?? "interested",
      ...patch
    }).select();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [
        { type: "text", text: `${existing ? "Updated" : "Added"} ${scholarshipName}.` }
      ],
      structuredContent: { application: data?.[0] }
    };
  }
});

// src/lib/mcp/tools/list-deadlines.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
var list_deadlines_default = defineTool5({
  name: "list_deadlines",
  title: "List upcoming deadlines",
  description: "List the signed-in student's upcoming GhanaPath deadlines.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("deadlines").select("id, title, category, due_date, notes").eq("user_id", ctx.getUserId()).order("due_date", { ascending: true });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const payload = { deadlines: data ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "hodvuidwrhlaildtcpww";
var mcp_default = defineMcp({
  name: "ghana-future-guide",
  title: "Ghana Future Guide",
  version: "0.1.0",
  instructions: "Tools for GhanaPath, a college, scholarship and career companion for Ghanaian students. Read the signed-in student's profile, saved universities and scholarships, tracked scholarship applications, deadlines and checklist, and add or update applications in their tracker.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_profile_default,
    list_saved_items_default,
    list_applications_default,
    track_application_default,
    list_deadlines_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
