-- GhanaPathFinder global source registry expansion
insert into public.source_registry(name,source_type,canonical_url,country_code,category,description,verified_at,last_checked_at,status,created_at,updated_at) values
('GhanaWeb','news','https://www.ghanaweb.com/','GH','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Citi Newsroom','news','https://citinewsroom.com/','GH','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('MyJoyOnline','news','https://www.myjoyonline.com/','GH','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Graphic Online','news','https://www.graphic.com.gh/','GH','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('3News','news','https://3news.com/','GH','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Pulse Ghana','news','https://www.pulse.com.gh/','GH','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Modern Ghana','news','https://www.modernghana.com/','GH','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Peace FM Online','news','https://www.peacefmonline.com/','GH','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Adom Online','news','https://www.adomonline.com/','GH','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('YEN.com.gh','news','https://yen.com.gh/','GH','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Business & Financial Times','news','https://thebftonline.com/','GH','business','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Ghana News Agency','news','https://gna.org.gh/','GH','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Daily Guide','news','https://dailyguidenetwork.com/','GH','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('The Chronicle Ghana','news','https://thechronicle.com.gh/','GH','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Class FM Online','news','https://www.classfmonline.com/','GH','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('TechCabal','news','https://techcabal.com/','NG','technology','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Techpoint Africa','news','https://techpoint.africa/','NG','technology','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Disrupt Africa','news','https://disruptafrica.com/','AF','startups','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('WeeTracker','news','https://weetracker.com/','AF','startups','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('BusinessDay Nigeria','news','https://businessday.ng/','NG','business','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Punch Nigeria','news','https://punchng.com/','NG','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Premium Times','news','https://www.premiumtimesng.com/','NG','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('The Guardian Nigeria','news','https://guardian.ng/','NG','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Vanguard Nigeria','news','https://www.vanguardngr.com/','NG','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('ThisDay Nigeria','news','https://www.thisdaylive.com/','NG','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Channels Television','news','https://www.channelstv.com/','NG','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('The Nation Nigeria','news','https://thenationonlineng.net/','NG','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Nairametrics','news','https://nairametrics.com/','NG','business','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Business Insider Africa','news','https://africa.businessinsider.com/','AF','business','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Ventures Africa','news','https://venturesafrica.com/','AF','business','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('How we made it in Africa','news','https://www.howwemadeitinafrica.com/','AF','business','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('African Business','news','https://african.business/','AF','business','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Forbes Africa','news','https://www.forbesafrica.com/','AF','business','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Africanews','news','https://www.africanews.com/','AF','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('The Africa Report','news','https://www.theafricareport.com/','AF','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('AllAfrica','news','https://allafrica.com/','AF','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Reuters Africa','news','https://www.reuters.com/world/africa/','AF','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('BBC Africa','news','https://www.bbc.com/news/world/africa','AF','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Al Jazeera Africa','news','https://www.aljazeera.com/where/africa/','AF','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('France 24 Africa','news','https://www.france24.com/en/africa/','AF','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('DW Africa','news','https://www.dw.com/en/africa/s-12756','AF','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('The EastAfrican','news','https://www.theeastafrican.co.ke/','KE','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Daily Nation Kenya','news','https://nation.africa/','KE','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('The Standard Kenya','news','https://www.standardmedia.co.ke/','KE','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Business Daily Africa','news','https://www.businessdailyafrica.com/','KE','business','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('The Star Kenya','news','https://www.the-star.co.ke/','KE','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Citizen Digital','news','https://citizen.digital/','KE','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('KBC Kenya','news','https://www.kbc.co.ke/','KE','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Capital News Kenya','news','https://www.capitalfm.co.ke/news/','KE','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Tuko Kenya','news','https://www.tuko.co.ke/','KE','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('People Daily Kenya','news','https://peopledaily.digital/','KE','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Techweez','news','https://techweez.com/','KE','technology','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('CIO Africa','news','https://cioafrica.co/','KE','technology','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('The Kenyan Wall Street','news','https://kenyanwallstreet.com/','KE','business','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Kenyans.co.ke','news','https://www.kenyans.co.ke/','KE','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Nairobi Wire','news','https://nairobiwire.com/','KE','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Africa Uncensored','news','https://africauncensored.online/','KE','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('The Elephant','news','https://www.theelephant.info/','KE','analysis','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Monitor Uganda','news','https://www.monitor.co.ug/','UG','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('New Vision Uganda','news','https://www.newvision.co.ug/','UG','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Nile Post','news','https://nilepost.co.ug/','UG','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('The Independent Uganda','news','https://www.independent.co.ug/','UG','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Uganda Radio Network','news','https://ugandaradionetwork.net/','UG','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('The New Times Rwanda','news','https://www.newtimes.co.rw/','RW','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('KT Press Rwanda','news','https://www.ktpress.rw/','RW','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Kigali Today','news','https://www.kigalitoday.com/','RW','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('IGIHE','news','https://www.igihe.com/','RW','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Rwanda Broadcasting Agency','news','https://www.rba.co.rw/','RW','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('The Citizen Tanzania','news','https://www.thecitizen.co.tz/','TZ','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Daily News Tanzania','news','https://dailynews.co.tz/','TZ','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('The Guardian Tanzania','news','https://www.ippmedia.com/','TZ','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Mwananchi Tanzania','news','https://www.mwananchi.co.tz/','TZ','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('The East African Business Week','news','https://www.busiweek.com/','UG','business','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Addis Standard','news','https://addisstandard.com/','ET','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Ethiopian News Agency','news','https://www.ena.et/en/','ET','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Fana Broadcasting Corporate','news','https://www.fanabc.com/english/','ET','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Ethiopian Broadcasting Corporation','news','https://www.ebc.et/','ET','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Walta Information Center','news','https://waltainfo.com/','ET','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('The Reporter Ethiopia','news','https://www.thereporterethiopia.com/','ET','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Capital Ethiopia','news','https://capitalethiopia.com/','ET','business','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Morocco World News','news','https://www.moroccoworldnews.com/','MA','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('TelQuel','news','https://telquel.ma/','MA','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Le Matin Morocco','news','https://lematin.ma/','MA','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('MAP Morocco','news','https://www.mapnews.ma/en','MA','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Hespress','news','https://en.hespress.com/','MA','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Ahram Online','news','https://english.ahram.org.eg/','EG','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Daily News Egypt','news','https://www.dailynewsegypt.com/','EG','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Egypt Today','news','https://www.egypttoday.com/','EG','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('EnterpriseAM Egypt','news','https://enterprise.press/','EG','business','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Mada Masr','news','https://www.madamasr.com/','EG','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Algeria Press Service','news','https://www.aps.dz/en','DZ','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Algeria Business','news','https://www.algeriabusiness.com/','DZ','business','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Tunis Afrique Presse','news','https://www.tap.info.tn/en','TN','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('La Presse Tunisia','news','https://lapresse.tn/','TN','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Business Daily Zambia','news','https://diggers.news/','ZM','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Zambia Daily Mail','news','https://www.daily-mail.co.zm/','ZM','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Lusaka Times','news','https://www.lusakatimes.com/','ZM','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('The Namibian','news','https://www.namibian.com.na/','NA','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('New Era Namibia','news','https://neweralive.na/','NA','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Botswana Gazette','news','https://www.thegazette.news/','BW','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Mmegi Botswana','news','https://www.mmegi.bw/','BW','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Malawi24','news','https://malawi24.com/','MW','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Nyasa Times','news','https://www.nyasatimes.com/','MW','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Mozambique Information Agency','news','https://aimnews.org/','MZ','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Angola Press','news','https://www.angop.ao/en/','AO','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Cameroon Tribune','news','https://www.cameroon-tribune.cm/','CM','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Journal du Cameroun','news','https://www.journalducameroun.com/','CM','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Sierra Leone Telegraph','news','https://www.thesierraleonetelegraph.com/','SL','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Liberian Observer','news','https://www.liberianobserver.com/','LR','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('The Point Gambia','news','https://thepoint.gm/','GM','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Foroyaa Gambia','news','https://foroyaa.net/','GM','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Seneweb','news','https://www.seneweb.com/','SN','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('APS Senegal','news','https://aps.sn/','SN','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Le Soleil Senegal','news','https://lesoleil.sn/','SN','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Dakaractu','news','https://www.dakaractu.com/','SN','news','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Africa Check','news','https://africacheck.org/','AF','factcheck','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('African Arguments','news','https://africanarguments.org/','AF','analysis','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('African Studies Review','news','https://www.cambridge.org/core/journals/african-studies-review','AF','research','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('African Journals Online','news','https://www.ajol.info/','AF','research','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('African Union','news','https://au.int/','AF','institution','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('African Development Bank','news','https://www.afdb.org/','AF','development','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('World Bank Africa','news','https://www.worldbank.org/en/region/afr','AF','development','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Smart Africa','news','https://smartafrica.org/','AF','technology','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('GSMA Africa','news','https://www.gsma.com/africa/','AF','technology','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Google Africa','news','https://africa.google/','AF','technology','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('Microsoft Africa','news','https://www.microsoft.com/en-africa','AF','technology','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now()),
('M-KOPA','news','https://www.m-kopa.com/','KE','technology','Publicly accessible source verified for GhanaPathFinder discovery',now(),now(),'active',now(),now())
on conflict (canonical_url) do update set last_checked_at=excluded.last_checked_at,status='active';