create table if not exists public.international_qualification_catalog (id uuid primary key default gen_random_uuid(),country_code text not null,country_name text not null,qualification_code text not null,qualification_name text not null,level text not null default 'secondary',notes text,source_url text,verification_status text not null default 'verified',last_verified_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(country_code,qualification_code));
create table if not exists public.international_pathway_rules (id uuid primary key default gen_random_uuid(),institution_id uuid not null references public.universities(id) on delete cascade,qualification_code text not null,academic_level text not null default 'undergraduate',minimum_overall_score numeric,score_operator text,required_subjects jsonb not null default '[]'::jsonb,equivalency_required boolean not null default false,english_proficiency_required boolean not null default false,notes text,source_url text not null,verification_status text not null default 'verified',last_verified_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(institution_id,qualification_code,academic_level));
create index if not exists idx_intl_qualification_country on public.international_qualification_catalog(country_code);
create index if not exists idx_intl_rule_qualification on public.international_pathway_rules(qualification_code);
create index if not exists idx_intl_rule_institution on public.international_pathway_rules(institution_id);
alter table public.international_qualification_catalog enable row level security;
alter table public.international_pathway_rules enable row level security;
drop policy if exists "public can read verified international qualifications" on public.international_qualification_catalog;
create policy "public can read verified international qualifications" on public.international_qualification_catalog for select to anon,authenticated using(verification_status='verified');
drop policy if exists "public can read verified international pathway rules" on public.international_pathway_rules;
create policy "public can read verified international pathway rules" on public.international_pathway_rules for select to anon,authenticated using(verification_status='verified');
grant select on public.international_qualification_catalog to anon,authenticated;
grant select on public.international_pathway_rules to anon,authenticated;
insert into public.international_qualification_catalog (country_code,country_name,qualification_code,qualification_name,notes,source_url,verification_status,last_verified_at) values
('GH','Ghana','WASSCE','West African Senior School Certificate Examination','Recognized Ghanaian secondary qualification.','https://admissions.ug.edu.gh/international/requirements','verified',now()),
('NG','Nigeria','WAEC_NIGERIA','West African Examinations Council Senior School Certificate','Foreign qualification; institutional/GTEC equivalence may be required.','https://www.knust.edu.gh/index.php/announcements/undergraduate-admissions/admission-candidates-undergraduate-degree-programmes-20262027-academic-year','verified',now()),
('NG','Nigeria','NECO','Senior School Certificate Examination (NECO)','Foreign qualification; institutional/GTEC equivalence may be required.','https://www.knust.edu.gh/index.php/announcements/undergraduate-admissions/admission-candidates-undergraduate-degree-programmes-20262027-academic-year','verified',now()),
('KE','Kenya','KCSE','Kenya Certificate of Secondary Education','Foreign qualification; formal equivalence may be required.','https://admissions.upsa.edu.gh/admissions/undergrad-entry-requirements/','verified',now()),
('SL','Sierra Leone','WASSCE_SL','West African Senior School Certificate Examination','Foreign WASSCE qualification; confirm equivalence.','https://www.knust.edu.gh/index.php/announcements/undergraduate-admissions/admission-candidates-undergraduate-degree-programmes-20262027-academic-year','verified',now()),
('LR','Liberia','WASSCE_LR','West African Senior School Certificate Examination','Foreign WASSCE qualification; confirm equivalence.','https://www.knust.edu.gh/index.php/announcements/undergraduate-admissions/admission-candidates-undergraduate-degree-programmes-20262027-academic-year','verified',now()),
('GM','Gambia','WASSCE_GM','West African Senior School Certificate Examination','Foreign WASSCE qualification; confirm equivalence.','https://www.knust.edu.gh/index.php/announcements/undergraduate-admissions/admission-candidates-undergraduate-degree-programmes-20262027-academic-year','verified',now()),
('ZA','South Africa','NSC','National Senior Certificate','Foreign qualification; formal equivalence may be required.','https://admissions.upsa.edu.gh/admissions/undergrad-entry-requirements/','verified',now()),
('GB','United Kingdom','A_LEVEL','GCE Advanced Level','Three relevant Advanced Level passes plus required O Level credits are commonly specified.','https://admissions.ug.edu.gh/international/requirements','verified',now()),
('US','United States','AMERICAN_HS','American High School Grade 12','UCC publishes a minimum final grade point of 3.0; other institutions may differ.','https://admissions.ucc.edu.gh/announcement/admission-of-regular-first-degree-students-20262027','verified',now()),
('INT','International','IB','International Baccalaureate','UCC publishes minimum HL/SL requirements; programme-specific requirements still apply.','https://admissions.ucc.edu.gh/announcement/admission-of-regular-first-degree-students-20262027','verified',now()),
('INT','International','IGCSE','International General Certificate of Secondary Education','Typically paired with Advanced Level results for degree admission.','https://admissions.ucc.edu.gh/announcement/admission-of-regular-first-degree-students-20262027','verified',now())
on conflict (country_code,qualification_code) do update set qualification_name=excluded.qualification_name,notes=excluded.notes,source_url=excluded.source_url,verification_status=excluded.verification_status,last_verified_at=excluded.last_verified_at,updated_at=now();

insert into public.international_pathway_rules (institution_id,qualification_code,academic_level,minimum_overall_score,score_operator,required_subjects,equivalency_required,notes,source_url,verification_status,last_verified_at) values
('e4e157e7-c4c3-48cd-9b2f-87a9e235137f','WASSCE','undergraduate',24,'<=','{"credits":"A1-C6","subjects":["English Language","Core Mathematics","Integrated Science or relevant science subject","3 relevant electives"]}',false,'UG published general international WASSCE requirement; programme-specific requirements apply.','https://admissions.ug.edu.gh/international/requirements','verified',now()),
('e4e157e7-c4c3-48cd-9b2f-87a9e235137f','A_LEVEL','undergraduate',null,null,'{"subjects":["3 relevant A Level subjects"],"o_level":["5 passes including English and Mathematics"]}',true,'Programme-specific A Level subjects apply.','https://admissions.ug.edu.gh/international/requirements','verified',now()),
('e4e157e7-c4c3-48cd-9b2f-87a9e235137f','IB','undergraduate',null,null,'{"hl":"3 relevant HL subjects","hl_minimum":4,"sl":["English Language/Literature","Mathematics"],"sl_minimum":4}',true,'Programme-specific IB subject requirements apply.','https://admissions.ug.edu.gh/international/requirements','verified',now()),
('fa5cf99e-b71b-45bb-9e66-141bc50b27ec','WASSCE','undergraduate',24,'<=','{"credits":"A1-C6","subjects":["3 core subjects including English and Mathematics","3 relevant electives"]}',false,'UCC 2026/2027 published basic requirement for local and international students.','https://admissions.ucc.edu.gh/announcement/admission-of-regular-first-degree-students-20262027','verified',now()),
('fa5cf99e-b71b-45bb-9e66-141bc50b27ec','A_LEVEL','undergraduate',null,null,'{"o_level":"5 credits including English and Mathematics","a_level":"3 relevant passes"}',true,'Published UCC general requirement; programme-specific requirements apply.','https://admissions.ucc.edu.gh/announcement/admission-of-regular-first-degree-students-20262027','verified',now()),
('fa5cf99e-b71b-45bb-9e66-141bc50b27ec','IGCSE','undergraduate',null,null,'{"o_level":"5 credits including English and Mathematics","a_level":"3 relevant passes"}',true,'Published UCC general requirement.','https://admissions.ucc.edu.gh/announcement/admission-of-regular-first-degree-students-20262027','verified',now()),
('fa5cf99e-b71b-45bb-9e66-141bc50b27ec','IB','undergraduate',null,null,'{"hl":"3 relevant HL subjects","hl_minimum":4,"health_hl_minimum":5,"sl":["English/Literature","Mathematics"],"sl_minimum":4}',true,'Published UCC general requirement.','https://admissions.ucc.edu.gh/announcement/admission-of-regular-first-degree-students-20262027','verified',now()),
('fa5cf99e-b71b-45bb-9e66-141bc50b27ec','AMERICAN_HS','undergraduate',3,'>=','{"metric":"final_grade_point"}',true,'Published UCC minimum final grade point of 3.0.','https://admissions.ucc.edu.gh/announcement/admission-of-regular-first-degree-students-20262027','verified',now()),
('a27e88aa-c280-4a2e-b30d-b2ac9e70802c','WASSCE','undergraduate',24,'<=','{"credits":"A1-C6","subjects":["English Language","Mathematics","Integrated Science","3 relevant electives"]}',false,'KNUST 2026/2027 published requirement; equivalent recognized qualifications may apply.','https://www.knust.edu.gh/index.php/announcements/undergraduate-admissions/admission-candidates-undergraduate-degree-programmes-20262027-academic-year','verified',now()),
('a27e88aa-c280-4a2e-b30d-b2ac9e70802c','A_LEVEL','undergraduate',null,null,'{"o_level":"5 credits including English and Mathematics","a_level":"3 relevant credit passes"}',true,'International applicants with equivalent recognized qualifications may apply.','https://www.knust.edu.gh/index.php/announcements/undergraduate-admissions/admission-candidates-undergraduate-degree-programmes-20262027-academic-year','verified',now()),
('a27e88aa-c280-4a2e-b30d-b2ac9e70802c','IB','undergraduate',null,null,'{"equivalence":"Equivalent to Ghanaian WASSCE/SSSCE or A Level requirements"}',true,'International IB applicants may apply with equivalent content; programme-specific requirements apply.','https://www.knust.edu.gh/index.php/announcements/undergraduate-admissions/admission-candidates-undergraduate-degree-programmes-20262027-academic-year','verified',now())
on conflict (institution_id,qualification_code,academic_level) do update set minimum_overall_score=excluded.minimum_overall_score,score_operator=excluded.score_operator,required_subjects=excluded.required_subjects,equivalency_required=excluded.equivalency_required,notes=excluded.notes,source_url=excluded.source_url,verification_status=excluded.verification_status,last_verified_at=excluded.last_verified_at,updated_at=now();