-- Backend expansion: user workflow persistence, recommendation history, documents, search alerts and auditability
-- Applied to production on 2026-09-21.

create table if not exists public.recommendation_runs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  run_type text not null default 'admissions',
  input_snapshot jsonb not null default '{}'::jsonb,
  engine_version text not null default 'v1',
  status text not null default 'completed' check (status in ('queued','running','completed','failed')),
  result_count integer not null default 0 check (result_count >= 0),
  error_message text,
  created_at timestamptz not null default now(),
  completed_at timestamptz
);
create table if not exists public.recommendation_items (
  id uuid primary key default gen_random_uuid(),
  run_id uuid not null references public.recommendation_runs(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  item_type text not null,
  entity_id uuid,
  rank integer not null check (rank > 0),
  score numeric(6,2),
  category text,
  explanation text,
  evidence jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique(run_id, rank)
);
create table if not exists public.application_notes (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  application_id uuid,
  title text not null,
  body text not null default '',
  is_private boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.user_documents (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  document_type text not null,
  file_name text not null,
  storage_path text not null,
  mime_type text,
  file_size_bytes bigint check (file_size_bytes is null or file_size_bytes >= 0),
  status text not null default 'active' check (status in ('active','archived','deleted')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.saved_searches (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  search_type text not null,
  filters jsonb not null default '{}'::jsonb,
  alerts_enabled boolean not null default false,
  last_run_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.user_activity (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  event_name text not null,
  entity_type text,
  entity_id uuid,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id uuid,
  before_data jsonb,
  after_data jsonb,
  created_at timestamptz not null default now()
);
