WITH raw(uslug, list) AS (VALUES
('knust','EN:BSc Electrical and Electronic Engineering|EN:BSc Mechanical Engineering|EN:BSc Civil Engineering|EN:BSc Chemical Engineering|EN:BSc Computer Engineering|EN:BSc Biomedical Engineering|EN:BSc Agricultural Engineering|GO:BSc Geomatic Engineering|EN:BSc Geological Engineering|EN:BSc Materials Engineering|EN:BSc Petroleum Engineering|EN:BSc Petrochemical Engineering|EN:BSc Telecommunication Engineering|EN:BSc Aerospace Engineering|EN:BSc Metallurgical Engineering|EN:BSc Marine Engineering|EN:BSc Automobile Engineering|EN:BSc Industrial Engineering|CS:BSc Computer Science|SC:BSc Mathematics|SC:BSc Statistics|SC:BSc Actuarial Science|SC:BSc Physics|SC:BSc Chemistry|SC:BSc Biochemistry|SC:BSc Biological Science|SC:BSc Food Science and Technology|EV:BSc Environmental Science|AG:BSc Agriculture|AG:BSc Agribusiness Management|EV:BSc Natural Resources Management|EV:BSc Forest Resources Technology|AG:BSc Aquaculture and Water Resources Management|VE:Doctor of Veterinary Medicine@6 years|ME:BSc Human Biology (Medicine)@6 years|ME:Doctor of Dental Surgery@6 years|PM:Doctor of Pharmacy@6 years|NU:BSc Nursing|MI:BSc Midwifery|HS:BSc Medical Laboratory Technology|HS:BSc Physician Assistantship|HS:BSc Sonography|HS:BSc Disability and Rehabilitation Studies|HS:BSc Herbal Medicine|AR:Bachelor of Architecture@6 years|CO:BSc Quantity Surveying and Construction Economics|CO:BSc Construction Technology and Management|BU:BSc Real Estate|BU:BSc Land Economy|DE:BSc Human Settlement Planning|DE:BSc Development Planning|BU:BSc Business Administration|AC:BSc Accounting|BU:BA Economics|DE:BA Sociology|DE:BA Social Work|PA:BA Political Studies|LG:BA English|LG:BA History|LG:BA French and Francophone Studies|GE:BA Religious Studies|LG:BA Akan Language and Culture|GE:BA Communication Design (Graphic Design)|GE:BA Painting and Sculpture|GE:BA Integrated Rural Art and Industry|GE:BA Publishing Studies|ED:BEd Junior High School Education'),
('university-of-ghana','CS:BSc Computer Science|IT:BSc Information Technology|EN:BSc Engineering (Biomedical)|EN:BSc Engineering (Computer)|EN:BSc Engineering (Agricultural)|EN:BSc Engineering (Food Process)|EN:BSc Engineering (Materials Science)|SC:BSc Mathematics|SC:BSc Statistics|SC:BSc Actuarial Science|SC:BSc Physics|SC:BSc Chemistry|SC:BSc Biochemistry|SC:BSc Botany|SC:BSc Zoology|SC:BSc Marine Science|SC:BSc Earth Science|SC:BSc Geology|PS:BSc Psychology|SC:BSc Nutrition and Food Science|AG:BSc Agriculture|AG:BSc Animal Science|AG:BSc Crop Science|AG:BSc Soil Science|AG:BSc Agricultural Economics|GE:BSc Family and Consumer Sciences|ME:Bachelor of Medicine and Bachelor of Surgery (MBChB)@7 years|PM:Doctor of Pharmacy@6 years|NU:BSc Nursing|MI:BSc Midwifery|HS:BSc Medical Laboratory Science|HS:BSc Physiotherapy|HS:BSc Radiography|HS:BSc Dietetics|HS:BSc Occupational Therapy|ME:Bachelor of Dental Surgery@6 years|PH:BSc Public Health|LA:LLB Law|AC:BSc Administration (Accounting)|FI:BSc Administration (Banking and Finance)|BU:BSc Administration (Marketing)|BU:BSc Administration (Human Resource Management)|FI:BSc Administration (Insurance)|PA:BSc Administration (Public Administration)|BU:BSc Administration (Health Services Management)|BU:BA Economics|PA:BA Political Science|DE:BA Sociology|DE:BA Social Work|IT:BA Information Studies|GE:BA Communication Studies|LG:BA English|LG:BA Linguistics|LG:BA French|LG:BA Spanish|LG:BA Russian|LG:BA Chinese|LG:BA Arabic|GE:BA Philosophy and Classics|GE:BA Study of Religions|LG:BA History|GE:BA Archaeology|EV:BA Geography and Resource Development|GE:BA Theatre Arts|GE:BA Dance Studies|GE:BA Music|GE:BFA Fine Art|ED:BA Adult Education|GE:BSc Family Studies'),
('university-of-cape-coast','CS:BSc Computer Science|IT:BSc Information Technology|SC:BSc Mathematics|SC:BSc Statistics|SC:BSc Actuarial Science|SC:BSc Physics|SC:BSc Chemistry|SC:BSc Biochemistry|SC:BSc Biological Sciences|SC:BSc Laboratory Technology|EV:BSc Environmental Science|AG:BSc Fisheries and Aquatic Sciences|AG:BSc Agriculture|AG:BSc Agri-Business|ME:Bachelor of Medicine and Bachelor of Surgery (MBChB)@6 years|NU:BSc Nursing|MI:BSc Midwifery|HS:BSc Medical Laboratory Science|HS:BSc Physician Assistant Studies|HS:BSc Optometry@6 years|PH:BSc Public Health|LA:LLB Law|AC:BCom Accounting|FI:BCom Finance|BU:BCom Marketing|BU:BCom Human Resource Management|BU:BCom Management|HO:BSc Tourism and Hospitality Management|BU:BSc Procurement and Supply Chain Management|BU:BA Economics|DE:BA Sociology|DE:BA Social Work|PH:BA Population and Health|EV:BA Geography and Regional Planning|GE:BA Communication Studies|LG:BA English|LG:BA French|LG:BA History|GE:BA Religion and Human Values|GE:BA Music|GE:BA Theatre Studies|ED:BEd Mathematics|ED:BEd Science|ED:BEd Social Sciences|ED:BEd Arts|ED:BEd Early Childhood Education|ED:BEd Special Education|ED:BEd Information Technology|ED:BEd Health, Physical Education and Recreation|ED:BEd Management|ED:BEd Accounting'),
('uew','ED:BEd Early Childhood Education|ED:BEd Basic Education|ED:BEd Special Education|ED:BEd Mathematics Education|ED:BEd Science Education|ED:BEd ICT Education|ED:BEd Social Studies Education|ED:BEd English Education|ED:BEd French Education|ED:BEd Ghanaian Language Education|ED:BEd Health Science Education|ED:BEd Agricultural Science Education|ED:BEd Business Education (Accounting)|ED:BEd Physical Education|ED:BEd Music Education|ED:BEd Art Education|CS:BSc Computer Science|ED:BSc Information Technology Education|SC:BSc Mathematics|SC:BSc Chemistry|SC:BSc Physics|SC:BSc Biology|EV:BSc Environmental Science|NU:BSc Nursing|AC:BSc Accounting|BU:BA Economics|GE:BA Communication and Media Studies|PS:BA Psychology|EV:BA Geography|GE:BA Theatre Arts'),
('umat','EN:BSc Mining Engineering|EN:BSc Geological Engineering|GO:BSc Geomatic Engineering|EN:BSc Mineral Engineering|EN:BSc Mechanical Engineering|EN:BSc Electrical and Electronic Engineering|EN:BSc Petroleum Engineering|EN:BSc Petroleum Geosciences and Engineering|EN:BSc Renewable Energy Engineering|EN:BSc Environmental and Safety Engineering|CS:BSc Computer Science and Engineering|IT:BSc Information Systems and Technology|SC:BSc Mathematics|DS:BSc Statistical Data Science|BU:BSc Economics and Industrial Organisation|BU:BSc Logistics and Transport Management|GO:BSc Land Administration and Information Systems'),
('uenr','CS:BSc Computer Science and Informatics|IT:BSc Information Technology|EN:BSc Renewable Energy Engineering|EN:BSc Civil Engineering|EN:BSc Mechanical Engineering|EN:BSc Electrical and Electronic Engineering|EN:BSc Agricultural Engineering|EN:BSc Petroleum Engineering|EV:BSc Natural Resources Management|EV:BSc Forest Resources Technology|EV:BSc Environmental Science|AG:BSc Agriculture|AG:BSc Agribusiness|AG:BSc Fisheries and Water Resources Management|SC:BSc Mathematics|SC:BSc Statistics|AC:BSc Accounting|BU:BSc Economics|BU:BSc Procurement and Supply Chain Management'),
('uhas','NU:BSc Nursing|MI:BSc Midwifery|PH:BSc Public Health (Disease Control)|PH:BSc Public Health (Health Promotion)|HS:BSc Medical Laboratory Science|HS:BSc Physician Assistantship|HS:BSc Physiotherapy and Sports Science|HS:BSc Dietetics|HS:BSc Nutrition|HS:BSc Speech, Language and Hearing Sciences|HS:BSc Medical Imaging Technology|ME:Doctor of Medicine (MBChB)@6 years|HS:BSc Health Information Management|HS:BSc Biomedical Sciences'),
('uds','AG:BSc Agriculture Technology|AG:BSc Agribusiness|AG:BSc Animal Science|EV:BSc Renewable Natural Resources|CS:BSc Computer Science|IT:BSc Information Technology|EN:BSc Agricultural Engineering|EN:BSc Mechanical Engineering|EN:BSc Civil Engineering|ME:Bachelor of Medicine and Bachelor of Surgery (MBChB)@6 years|NU:BSc Nursing|MI:BSc Midwifery|HS:BSc Medical Laboratory Science|HS:BSc Community Nutrition|PH:BSc Public Health|DE:BSc Development Studies|DE:BA Integrated Community Development|FI:BSc Banking and Finance|AC:BSc Accounting|BU:BA Economics|LA:LLB Law'),
('cktutas','CS:BSc Computer Science|IT:BSc Information Technology|SC:BSc Mathematics|SC:BSc Statistics|SC:BSc Applied Physics|SC:BSc Applied Chemistry|SC:BSc Biotechnology|EV:BSc Environmental Science|AG:BSc Agriculture|NU:BSc Nursing|MI:BSc Midwifery|PH:BSc Public Health|AC:BSc Accounting|BU:BSc Business Administration'),
('aamusted','TE:BEd Automotive Engineering Technology|TE:BEd Mechanical Engineering Technology|TE:BEd Electrical and Electronic Technology|TE:BEd Construction Technology|TE:BEd Wood Technology|HO:BEd Catering and Hospitality|TE:BEd Fashion Design and Textiles|ED:BEd Accounting Education|ED:BEd Management Education|ED:BEd Information Technology Education|ED:BEd Agricultural Science Education|BU:BSc Entrepreneurship'),
('atu','EN:BTech Civil Engineering|EN:BTech Mechanical Engineering|EN:BTech Electrical and Electronic Engineering|CS:BTech Computer Science|IT:BTech Information and Communication Technology|AC:BTech Accountancy|BU:BTech Marketing|BU:BTech Procurement and Supply Chain Management|HO:BTech Hospitality Management|GE:BTech Fashion Design and Textiles|CO:BTech Building Technology|EN:HND Civil Engineering|EN:HND Electrical and Electronic Engineering|EN:HND Mechanical Engineering|AC:HND Accountancy|BU:HND Marketing|HO:HND Hotel Catering and Institutional Management'),
('ktu','EN:BTech Civil Engineering|EN:BTech Mechanical Engineering|EN:BTech Electrical and Electronic Engineering|CS:BTech Computer Science|AC:BTech Accountancy|BU:BTech Procurement and Supply Chain Management|HO:BTech Hospitality and Tourism Management|EN:HND Civil Engineering|EN:HND Mechanical Engineering|EN:HND Electrical and Electronic Engineering|AC:HND Accountancy|BU:HND Marketing|SC:HND Statistics|CS:HND Computer Science'),
('kstu','EN:BTech Civil Engineering|EN:BTech Mechanical Engineering|EN:BTech Electrical and Electronic Engineering|CS:BTech Computer Science|AC:BTech Accountancy|BU:BTech Procurement and Supply Chain Management|HO:BTech Hospitality and Tourism Management|EN:HND Civil Engineering|EN:HND Mechanical Engineering|EN:HND Electrical and Electronic Engineering|AC:HND Accountancy|BU:HND Marketing|SC:HND Statistics|CS:HND Computer Science'),
('cctu','EN:BTech Civil Engineering|EN:BTech Mechanical Engineering|EN:BTech Electrical and Electronic Engineering|CS:BTech Computer Science|AC:BTech Accountancy|BU:BTech Procurement and Supply Chain Management|HO:BTech Hospitality and Tourism Management|EN:HND Civil Engineering|EN:HND Mechanical Engineering|EN:HND Electrical and Electronic Engineering|AC:HND Accountancy|BU:HND Marketing|SC:HND Statistics|CS:HND Computer Science'),
('stu','EN:BTech Civil Engineering|EN:BTech Mechanical Engineering|EN:BTech Electrical and Electronic Engineering|CS:BTech Computer Science|AC:BTech Accountancy|BU:BTech Procurement and Supply Chain Management|HO:BTech Hospitality and Tourism Management|EN:HND Civil Engineering|EN:HND Mechanical Engineering|EN:HND Electrical and Electronic Engineering|AC:HND Accountancy|BU:HND Marketing|SC:HND Statistics|CS:HND Computer Science'),
('tatu','EN:BTech Civil Engineering|EN:BTech Mechanical Engineering|EN:BTech Electrical and Electronic Engineering|CS:BTech Computer Science|AC:BTech Accountancy|BU:BTech Procurement and Supply Chain Management|HO:BTech Hospitality and Tourism Management|EN:HND Civil Engineering|EN:HND Mechanical Engineering|EN:HND Electrical and Electronic Engineering|AC:HND Accountancy|BU:HND Marketing|SC:HND Statistics|CS:HND Computer Science'),
('htu','EN:BTech Civil Engineering|EN:BTech Mechanical Engineering|EN:BTech Electrical and Electronic Engineering|CS:BTech Computer Science|AC:BTech Accountancy|BU:BTech Procurement and Supply Chain Management|HO:BTech Hospitality and Tourism Management|EN:HND Civil Engineering|EN:HND Mechanical Engineering|EN:HND Electrical and Electronic Engineering|AC:HND Accountancy|BU:HND Marketing|SC:HND Statistics|CS:HND Computer Science'),
('ttu','EN:BTech Civil Engineering|EN:BTech Mechanical Engineering|EN:BTech Electrical and Electronic Engineering|CS:BTech Computer Science|AC:BTech Accountancy|BU:BTech Procurement and Supply Chain Management|HO:BTech Hospitality and Tourism Management|EN:HND Civil Engineering|EN:HND Mechanical Engineering|EN:HND Electrical and Electronic Engineering|AC:HND Accountancy|BU:HND Marketing|SC:HND Statistics|CS:HND Computer Science|EN:BTech Marine Engineering'),
('btu','EN:BTech Civil Engineering|EN:BTech Mechanical Engineering|EN:BTech Electrical and Electronic Engineering|CS:BTech Computer Science|AC:BTech Accountancy|BU:BTech Procurement and Supply Chain Management|HO:BTech Hospitality and Tourism Management|EN:HND Civil Engineering|EN:HND Mechanical Engineering|EN:HND Electrical and Electronic Engineering|AC:HND Accountancy|BU:HND Marketing|SC:HND Statistics|CS:HND Computer Science'),
('gctu','CS:BSc Computer Science|IT:BSc Information Technology|CY:BSc Cyber Security|DS:BSc Data Science and Analytics|EN:BSc Telecommunications Engineering|EN:BSc Computer Engineering|EN:BSc Electrical and Electronic Engineering|IT:BSc Information Systems|BU:BSc Business Administration|AC:BSc Accounting and Finance|BU:BSc Procurement and Logistics Management'),
('ashesi','CS:BSc Computer Science|IT:BSc Management Information Systems|BU:BSc Business Administration|EN:BSc Computer Engineering|EN:BSc Electrical and Electronic Engineering|EN:BSc Mechanical Engineering|EN:BSc Mechatronics Engineering'),
('academic-city','CS:BSc Computer Science|EN:BSc Computer Engineering|EN:BSc Electrical and Electronic Engineering|EN:BSc Mechanical Engineering|EN:BSc Mechatronics Engineering|BU:BSc Business Administration|IT:BSc Management Information Systems|EN:BSc Robotics Engineering'),
('upsa','AC:BSc Accounting|FI:BSc Banking and Finance|BU:BSc Marketing|BU:BSc Business Administration|IT:BSc Information Technology Management|BU:BSc Procurement and Supply Chain Management|BU:BSc Real Estate Management|SC:BSc Actuarial Science|GE:BSc Public Relations Management|LA:LLB Law|BU:BSc Human Resource Management'),
('gimpa','AC:BSc Accounting and Finance|BU:BSc Business Administration|IT:BSc Management Information Systems|CS:BSc Computer Science|PA:BSc Public Administration|LA:LLB Law|BU:BSc Economics'),
('central-university','BU:BSc Business Administration|AC:BSc Accounting|FI:BSc Banking and Finance|IT:BSc Information Technology|CS:BSc Computer Science|NU:BSc Nursing|BU:BSc Human Resource Management|LA:LLB Law|GE:BA Communication Studies|GE:BA Theology'),
('valley-view','CS:BSc Computer Science|IT:BSc Information Technology|NU:BSc Nursing|AC:BSc Accounting|BU:BSc Business Administration|AG:BSc Agribusiness|GE:BA Theology|PH:BSc Public Health'),
('pentecost-university','CS:BSc Computer Science|IT:BSc Information Technology|CY:BSc Cyber Security|AC:BSc Accounting and Finance|BU:BSc Business Administration|GE:BA Theology|NU:BSc Nursing'),
('all-nations','CS:BSc Computer Science|IT:BSc Information Technology|EN:BSc Electrical and Electronic Engineering|EN:BSc Biomedical Engineering|BU:BSc Business Administration|NU:BSc Nursing|GE:BA Theology'),
('regent','CS:BSc Computer Science|IT:BSc Information Technology|EN:BSc Electrical and Electronic Engineering|BU:BSc Business Administration|AC:BSc Accounting|GE:BA Theology'),
('knutsford','BU:BSc Business Administration|AC:BSc Accounting and Finance|IT:BSc Information Technology|LA:LLB Law|BU:BSc Marketing'),
('csuc','CS:BSc Computer Science|BU:BSc Business Administration|AC:BSc Accounting|NU:BSc Nursing|GE:BA Communication Studies|GE:BA Theology'),
('catholic-university','NU:BSc Nursing|BU:BSc Business Administration|CS:BSc Computer Science|BU:BSc Economics|GE:BA Religious Studies|PH:BSc Public Health'),
('methodist-university','BU:BSc Business Administration|AC:BSc Accounting|IT:BSc Information Technology|NU:BSc Nursing|BU:BA Human Resource Management|GE:BA Theology'),
('presby-university','BU:BSc Business Administration|IT:BSc Information Technology|NU:BSc Nursing|AG:BSc Agriculture|GE:BA Theology'),
('bluecrest','IT:BSc Information Technology|CS:BSc Software Engineering|GE:BA Graphic Design|GE:BA Fashion Design|BU:BSc Business Administration|FL:BA Multimedia and Animation'),
('webster-ghana','GE:BA Media Communications|BU:BSc Business Administration|PA:BA International Relations|BU:BSc Management'),
('lancaster-ghana','CS:BSc Computer Science|BU:BSc Business Management|AC:BSc Accounting and Finance|LA:LLB Law'),
('iug','BU:BSc Business Administration|IT:BSc Information Technology|NU:BSc Nursing|GE:BA Islamic Studies|PH:BSc Public Health'),
('gcuc','NU:BSc Nursing|HS:BSc Physician Assistantship|BU:BSc Business Administration|CS:BSc Computer Science|PH:BSc Public Health'),
('radford','BU:BSc Business Administration|IT:BSc Information Technology|GE:BA Communication Studies|AC:BSc Accounting'),
('kings-university','BU:BSc Business Administration|IT:BSc Information Technology|NU:BSc Nursing|GE:BA Theology')
), items AS (
  SELECT r.uslug, trim(x) AS entry FROM raw r, unnest(string_to_array(r.list,'|')) AS x
), parsed AS (
  SELECT uslug,
    split_part(entry,':',1) AS code,
    split_part(split_part(entry,':',2),'@',1) AS pname,
    NULLIF(split_part(entry,'@',2),'') AS dur_override
  FROM items
), final AS (
  SELECT u.id AS university_id,
    lower(regexp_replace(p.uslug||'-'||replace(p.pname,'&','and'),'[^a-zA-Z0-9]+','-','g')) AS slug,
    p.pname AS name,
    CASE code WHEN 'EN' THEN 'Engineering' WHEN 'CS' THEN 'Computer Science' WHEN 'IT' THEN 'Information Technology' WHEN 'DS' THEN 'Data Science' WHEN 'CY' THEN 'Cybersecurity' WHEN 'AI' THEN 'Artificial Intelligence' WHEN 'BU' THEN 'Business' WHEN 'AC' THEN 'Accounting' WHEN 'FI' THEN 'Finance' WHEN 'SC' THEN 'Applied Sciences' WHEN 'HS' THEN 'Health Sciences' WHEN 'LA' THEN 'Law' WHEN 'ED' THEN 'Education' WHEN 'AG' THEN 'Agriculture' WHEN 'AR' THEN 'Architecture' WHEN 'CO' THEN 'Construction' WHEN 'EV' THEN 'Environment' WHEN 'PS' THEN 'Psychology' WHEN 'PH' THEN 'Public Health' WHEN 'DE' THEN 'Development' WHEN 'LG' THEN 'Languages' WHEN 'HO' THEN 'Hospitality' WHEN 'PA' THEN 'Public Administration' WHEN 'GE' THEN 'General' WHEN 'ME' THEN 'Medicine' WHEN 'PM' THEN 'Pharmacy' WHEN 'NU' THEN 'Nursing' WHEN 'MI' THEN 'Midwifery' WHEN 'GO' THEN 'Geomatic Engineering' WHEN 'FL' THEN 'Film and Television' WHEN 'TE' THEN 'Technical Education' WHEN 'VE' THEN 'Veterinary Science' ELSE 'General' END AS field,
    COALESCE(p.dur_override, CASE WHEN p.pname LIKE 'HND%' THEN '3 years' ELSE '4 years' END) AS duration,
    CASE WHEN p.pname LIKE 'HND%' THEN 'HND' ELSE 'Bachelor''s degree' END AS qualification,
    CASE WHEN p.pname LIKE 'HND%' THEN 'HND' ELSE 'Bachelor' END AS degree_type
  FROM parsed p JOIN public.universities u ON u.slug = p.uslug
)
INSERT INTO public.programmes (university_id, slug, name, degree_type, field, duration, qualification, verification_status, verified, relevant_subjects, career_opportunities)
SELECT university_id, trim(both '-' from slug), name, degree_type, field, duration, qualification, 'unverified', false, '{}'::text[], '{}'::text[]
FROM final
ON CONFLICT DO NOTHING;

CREATE INDEX IF NOT EXISTS idx_programmes_degree_type ON public.programmes (degree_type);
CREATE INDEX IF NOT EXISTS idx_programmes_qualification ON public.programmes (qualification);
CREATE INDEX IF NOT EXISTS idx_programmes_name ON public.programmes (name);