INSERT INTO public.institutions
  (official_name, institution_type, gtec_accreditation_status, region, town, website_url, short_description, needs_review, source_urls)
VALUES
  ('Akenten Appiah-Menka University of Skills Training and Entrepreneurial Development', 'Public University', 'Accredited', 'Ashanti', 'Kumasi', 'https://www.aamusted.edu.gh', 'Public university for skills training, technical and vocational education and entrepreneurial development, with campuses in Kumasi and Asante Mampong.', true, ARRAY['https://www.aamusted.edu.gh','https://gtec.edu.gh']),
  ('Bolgatanga Technical University', 'Technical University', 'Accredited', 'Upper East', 'Bolgatanga', 'https://bolgatu.edu.gh', 'Public technical university in Bolgatanga offering career-focused engineering, applied science and business programmes.', true, ARRAY['https://bolgatu.edu.gh','https://gtec.edu.gh']),
  ('Sunyani Technical University', 'Technical University', 'Accredited', 'Bono', 'Sunyani', 'https://www.stu.edu.gh', 'Public technical university in Sunyani with engineering, applied science, business and creative arts faculties.', true, ARRAY['https://www.stu.edu.gh','https://gtec.edu.gh']),
  ('Tamale Technical University', 'Technical University', 'Accredited', 'Northern', 'Tamale', 'https://tatu.edu.gh', 'Public technical university in Tamale offering hands-on engineering, business and applied science training.', true, ARRAY['https://tatu.edu.gh','https://gtec.edu.gh']),
  ('Koforidua Technical University', 'Technical University', 'Accredited', 'Eastern', 'Koforidua', 'https://www.ktu.edu.gh', 'Public technical university in Koforidua known for engineering, computing and business programmes.', true, ARRAY['https://www.ktu.edu.gh','https://gtec.edu.gh']),
  ('Cape Coast Technical University', 'Technical University', 'Accredited', 'Central', 'Cape Coast', 'https://cctu.edu.gh', 'Public technical university in Cape Coast offering technical, vocational and business-oriented higher education.', true, ARRAY['https://cctu.edu.gh','https://gtec.edu.gh']),
  ('Dr. Hilla Limann Technical University', 'Technical University', 'Accredited', 'Upper West', 'Wa', 'https://dhltu.edu.gh', 'Public technical university in Wa serving the Upper West Region with applied technical and business programmes.', true, ARRAY['https://dhltu.edu.gh','https://gtec.edu.gh']),
  ('University of Environment and Sustainable Development', 'Public University', 'Accredited', 'Eastern', 'Somanya', 'https://uesd.edu.gh', 'Public university in Somanya specialising in environment, sustainability, natural resources and green technology.', true, ARRAY['https://uesd.edu.gh','https://gtec.edu.gh']),
  ('University of Media, Arts and Communication', 'Public University', 'Accredited', 'Greater Accra', 'Accra', 'https://unimac.edu.gh', 'Public university formed from the Ghana Institute of Journalism, NAFTI and the Ghana Institute of Languages, focused on media, arts and communication.', true, ARRAY['https://unimac.edu.gh','https://gtec.edu.gh']),
  ('Accra Institute of Technology', 'Private University', 'Accredited', 'Greater Accra', 'Accra', 'https://ait.edu.gh', 'Private institution in Accra offering engineering, computing and business degrees with open and distance learning options.', true, ARRAY['https://ait.edu.gh','https://gtec.edu.gh']),
  ('Ghana Baptist University College', 'Private University College', 'Accredited', 'Ashanti', 'Kumasi', 'https://www.gbuc.edu.gh', 'Faith-based private university college in Kumasi offering theology, business, education and applied science programmes.', true, ARRAY['https://www.gbuc.edu.gh','https://gtec.edu.gh']),
  ('Lancaster University Ghana', 'Private University', 'Accredited', 'Greater Accra', 'Accra', 'https://lancaster.edu.gh', 'Accra campus of Lancaster University awarding UK degrees in business, computing and law.', true, ARRAY['https://lancaster.edu.gh','https://gtec.edu.gh']),
  ('BlueCrest University College', 'Private University College', 'Accredited', 'Greater Accra', 'Accra', 'https://bluecrest.edu.gh', 'Private university college in Accra specialising in media, fashion, computing and business programmes.', true, ARRAY['https://bluecrest.edu.gh','https://gtec.edu.gh']),
  ('Ensign Global University', 'Private University', 'Accredited', 'Eastern', 'Kpong', 'https://ensign.edu.gh', 'Private graduate institution in Kpong focused on public health and global health leadership.', true, ARRAY['https://ensign.edu.gh','https://gtec.edu.gh']),
  ('Heritage Christian University', 'Private University', 'Accredited', 'Greater Accra', 'Amasaman', 'https://hcuc.edu.gh', 'Private Christian university offering business, nursing, education and theology programmes.', true, ARRAY['https://hcuc.edu.gh','https://gtec.edu.gh']),
  ('Islamic University of Ghana', 'Private University', 'Accredited', 'Greater Accra', 'East Legon', 'https://www.iug.edu.gh', 'Private university in Accra offering business, IT, Islamic studies and social science programmes.', true, ARRAY['https://www.iug.edu.gh','https://gtec.edu.gh']),
  ('Ghana Christian University College', 'Private University College', 'Accredited', 'Greater Accra', 'Amrahia', 'https://gcuc.edu.gh', 'Private Christian university college offering theology, business administration and development studies.', true, ARRAY['https://gcuc.edu.gh','https://gtec.edu.gh'])
ON CONFLICT DO NOTHING;