-- GhanaPathFinder backend expansion
-- Production schema for recommendation history, application notes, documents,
-- saved searches, user activity and administrative auditability.

create extension if not exists pgcrypto;

create table if not exists public.recommendation_runs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  run_type text not null default 'admissions',
  input_snapshot jsonb not null default '{}'::jsonb,
  engine_version text not null default 'v1',
  status text not null default 'completed' check (status in ('queued','running','completed','failed')),
  result_count integer not null default 0 check (result_count >= 0),
  error_message text,
  created_at timestamptz not null default now(),
  completed_at timestamptz
);

create table if not exists public.recommendation_items (
  id uuid primary key default gen_random_uuid(),
  run_id uuid not null references public.recommendation_runs(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  item_type text not null,
  entity_id uuid,
  rank integer not null check (rank > 0),
  score numeric(6,2),
  category text,
  explanation text,
  evidence jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique(run_id, rank)
);

create table if not exists public.application_notes (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  application_id uuid,
  title text not null,
  body text not null default '',
  is_private boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.user_documents (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  document_type text not null,
  file_name text not null,
  storage_path text not null,
  mime_type text,
  file_size_bytes bigint check (file_size_bytes is null or file_size_bytes >= 0),
  status text not null default 'active' check (status in ('active','archived','deleted')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.saved_searches (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  search_type text not null,
  filters jsonb not null default '{}'::jsonb,
  alerts_enabled boolean not null default false,
  last_run_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.user_activity (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  event_name text not null,
  entity_type text,
  entity_id uuid,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id uuid,
  before_data jsonb,
  after_data jsonb,
  created_at timestamptz not null default now()
);

create index if not exists recommendation_runs_user_created_idx on public.recommendation_runs(user_id, created_at desc);
create index if not exists recommendation_items_run_rank_idx on public.recommendation_items(run_id, rank);
create index if not exists recommendation_items_user_type_idx on public.recommendation_items(user_id, item_type);
create index if not exists application_notes_user_updated_idx on public.application_notes(user_id, updated_at desc);
create index if not exists user_documents_user_type_idx on public.user_documents(user_id, document_type);
create index if not exists saved_searches_user_type_idx on public.saved_searches(user_id, search_type);
create index if not exists user_activity_user_created_idx on public.user_activity(user_id, created_at desc);
create index if not exists admin_audit_actor_created_idx on public.admin_audit_log(actor_id, created_at desc);

alter table public.recommendation_runs enable row level security;
alter table public.recommendation_items enable row level security;
alter table public.application_notes enable row level security;
alter table public.user_documents enable row level security;
alter table public.saved_searches enable row level security;
alter table public.user_activity enable row level security;
alter table public.admin_audit_log enable row level security;

drop policy if exists recommendation_runs_owner_select on public.recommendation_runs;
create policy recommendation_runs_owner_select on public.recommendation_runs for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists recommendation_runs_owner_insert on public.recommendation_runs;
create policy recommendation_runs_owner_insert on public.recommendation_runs for insert to authenticated with check ((select auth.uid()) = user_id);

drop policy if exists recommendation_items_owner_select on public.recommendation_items;
create policy recommendation_items_owner_select on public.recommendation_items for select to authenticated using ((select auth.uid()) = user_id);

drop policy if exists application_notes_owner_all on public.application_notes;
create policy application_notes_owner_all on public.application_notes for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

drop policy if exists user_documents_owner_all on public.user_documents;
create policy user_documents_owner_all on public.user_documents for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

drop policy if exists saved_searches_owner_all on public.saved_searches;
create policy saved_searches_owner_all on public.saved_searches for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

drop policy if exists user_activity_owner_select on public.user_activity;
create policy user_activity_owner_select on public.user_activity for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists user_activity_owner_insert on public.user_activity;
create policy user_activity_owner_insert on public.user_activity for insert to authenticated with check ((select auth.uid()) = user_id);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists application_notes_touch on public.application_notes;
create trigger application_notes_touch before update on public.application_notes for each row execute function public.touch_updated_at();
drop trigger if exists user_documents_touch on public.user_documents;
create trigger user_documents_touch before update on public.user_documents for each row execute function public.touch_updated_at();
drop trigger if exists saved_searches_touch on public.saved_searches;
create trigger saved_searches_touch before update on public.saved_searches for each row execute function public.touch_updated_at();

create or replace function public.get_user_backend_snapshot()
returns jsonb
language plpgsql
security invoker
set search_path = public
as $$
declare uid uuid := (select auth.uid());
begin
  if uid is null then raise exception 'not_authenticated'; end if;
  return jsonb_build_object(
    'profile', (select to_jsonb(p) from public.profiles p where p.id = uid),
    'student_profile', (select to_jsonb(sp) from public.student_profiles sp where sp.user_id = uid),
    'wassce_results', coalesce((select jsonb_agg(to_jsonb(w) order by w.subject) from public.wassce_results w where w.user_id = uid), '[]'::jsonb),
    'saved_items', coalesce((select jsonb_agg(to_jsonb(s) order by s.created_at desc) from public.saved_items s where s.user_id = uid), '[]'::jsonb),
    'match_preferences', (select to_jsonb(m) from public.match_preferences m where m.user_id = uid),
    'notification_preferences', (select to_jsonb(n) from public.notification_preferences n where n.user_id = uid)
  );
end;
$$;

revoke all on function public.get_user_backend_snapshot() from public;
grant execute on function public.get_user_backend_snapshot() to authenticated;

-- Security hardening for existing profile persistence functions.
alter function public.save_profile_bundle(text,text,text,text,text,text,text[],text[],text,text,text,text,jsonb,jsonb,jsonb) security invoker;
alter function public.save_profile_bundle(text,text,text,text,text,text,text[],text[],text,text,text,text,jsonb,jsonb,jsonb,text,text) security invoker;

drop policy if exists admin_audit_log_owner_select on public.admin_audit_log;
create policy admin_audit_log_owner_select on public.admin_audit_log for select to authenticated using ((select auth.uid()) = actor_id);
